README.md
...to the head of the README file
=> Add Che repo link

src/helpers/helm.ts, yarn.lock
The PR fixes two issues:
- waits until a Tiller pod is running and ready to receive the requests instead of waiting 10 sec.
- gives a Tiller pod more time to start (10->20 sec.) before the command will be terminated
fixes #8
=> More stable running a Tiller pod

src/helpers/minikube.ts
=> Give minikube more time to start a local cluster

.travis.yml, README.md, yarn.lock
=> Fix installation section in README

package.json, src/commands/server/start.ts
=> Fix EEXIST error when copying file to chectl cache

README.md
Added links to minikube and helm installation instructions
=> Added prerequisites in README.md

.gitignore
Change-Id: I07656cea96ebe6128a1717c5e0d83d6ed1f11992
=> Ignore generated tgz files

README.md, ambient.d.ts, package.json, src/commands/server/start.ts, test/helpers/che.test.ts, tsconfig.json, yarn.lock
Look at separate commits
BTW somehow the automated generate doc is failing
for ` -t, --templates=templates`
it displays my username by default ? (or mloriedo before)
=> Some fixes

.gitignore, package.json, yarn.lock
Also add yarn run test-watch
Change-Id: Ie24c30a45235e65c74de545c7ef2ea29e3fdd17b
=> Use jest instead of all the other tools

package.json, test/api/che.test.ts, test/platforms/minikube.test.ts, yarn.lock
enable platforms tests
Change-Id: I9c824a15e76dfd7c694027b4c8122b51bb802c97
=> Remove the use of proxyquire and sinon, using pure jest stuff

src/installers/helm.ts
The timeout issue was the cause of #27. In particular 20s were often not enough to create the Tiller service, in particular the first time, when the image has to be pulled.
I have set 30s timeouts for most of the check if exist tasks and more when the task includes the creation of kubernetes objects or the download of some images or dependencies.
=> Increase timeouts and add better error checking

README.md, src/api/kube.ts, src/api/openshift.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts, src/installers/operator.ts, src/platforms/minishift.ts, test/api/che.test.ts, test/api/kube.test.ts, test/api/openshift.test.ts, test/api/replies/create-workspace-from-valid-devfile.json, test/api/replies/create-workspace-from-valid-workspaceconfig.json, test/api/replies/get-deployment-che-available.json, test/api/replies/get-deployment-che-progressing.json, test/api/replies/get-deployment-che-running.json, test/api/replies/get-pod-by-selector-pending.json, test/api/replies/get-pod-by-selector-ready.json, test/api/replies/get-pod-by-selector-running-ready.json, test/api/replies/get-pod-by-selector-running.json, test/api/replies/get-pods-che-running.json, test/platforms/minishift.test.ts
Added minishift as a new installation platform. 
I have also changed the default namespace name to `che` because we cannot create namespaces prefixed with `kube-` on OpenShift.
=> Minishift support

src/platforms/minishift.ts
Fixes #64
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> Replace minikube by minishift

src/installers/helm.ts
Fixes #57
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> Fix multi line command for Windows

src/platforms/minishift.ts
Fixes #66
Signed-off-by: Jeff MAURY <jmaury@redhat.com>
=> Switch minishift status timeout to 1mn

devfile.yaml
Update Che Devfile in accordance with the latest Che upstream changes.
See https://github.com/eclipse/che/pull/12965 and https://github.com/eclipse/che/pull/12964 for the details.
=> Update Che Devfile

.travis.yml
Fixes #74 
Change-Id: I72ebe455f3a34ce15ba7c4260c34439437d2e8c9
=> Fix #74 : Predefine memory options to avoid FLAGS_MISMATCH if user customize NODE_OPTIONS env var

.gitignore, Jenkinsfile, README.md, yarn.lock
Signed-off-by:...
#72 - initial commit
=> #72 - Jenkinsfile to build chectl and publish to dl.jboss.org

templates/che-operator/config.yaml
Change comment about default plugin registry value since it was changed
=> WIP Fix comment about registry

README.md
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Specify that userland-proxy option should be set to false

README.md, src/platforms/minikube.ts, src/platforms/minishift.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts
Fixes #107
Change-Id: I54a68447a375436b5a6f925b6c90bb67115dfcd0
=> userland-proxy=false is not required anymore

src/commands/server/start.ts
Change-Id: I956a292cca4fbc6a898e83f9afbafd7f90750986
=> Fixes #101: check for minishift platform for minishift addon

src/api/openshift.ts, src/commands/server/start.ts, src/installers/minishift-addon.ts
First, check that we're logged with oc tool
Second, check that the addon is there before trying to apply it (else we're in a kind of infinite waiting loop)
It fixes #91
=> [minishit addon] Adds checks

README.md, src/api/kube.ts, src/commands/devfile/generate.ts, src/commands/server/delete.ts, src/commands/server/start.ts, src/installers/operator.ts, test/api/kube.test.ts
It introduces two new flag to override wait and ready timeout
Fixes #97 and #98
Change-Id: Ic3f3b7d2acbce49796972c30c45fcd63c3d4db78
=> Introduce a configurable timeout when starting chectl

src/installers/minishift-addon.ts, test/installers/minishift-addon.test.ts
=> Ensure minishift version is 1.33 or higher when using minishift-addon

package.json, yarn.lock
=> Fix CVE https://nvd.nist.gov/vuln/detail/CVE-2019-10742

devfile.yaml, src/api/devfile.ts, src/commands/devfile/generate.ts, test/api/replies/create-workspace-from-invalid-devfile.json, test/api/requests/devfile.valid
This makes chectl compatible with Che 7 RC2.
=> Update to the latest version of the devfile API.

.travis.yml
required for https://github.com/che-incubator/chectl/pull/155
Change-Id: Ia45deff4f843e33e4b9e5bf5144a63478847fe75
=> Provide binaries in releases section with .gz version of chectl

.travis.yml
it's solving issue of running on windows
Fixes #167
=> Use a fixed version of pkg instead of always taking the latest

package.json
Fixes https://github.com/che-incubator/chectl/issues/177
=> Remove unused package

Jenkinsfile
fix path where files end up after the build
Change-Id: I2c189cf1d760617deb4c1d421501ef09be8999e9
=> fix path where files end up after the build; do not generate json files as the build now produces them

.travis.yml
Also need to make udpate of homebrew as brew is not always up-to-date even if it is said so by Travis-CI
Change-Id: I07687daf561893e128566f8831baef1c37dd24d8
=> Move brew installation of 7z only to deploy phase so it's not slowing all PR builds

src/api/che.ts, test/api/che.test.ts, test/api/replies/create-workspace-from-valid-devfile.json
Fixes https://github.com/eclipse/che/issues/13623
=> fix: update che API devfile endpoint

.github/ISSUE_TEMPLATE/where-to-report-issues.md, README.md
It's part of https://github.com/eclipse/che/issues/13637 endgame
=> docs(gh): create issues in main Eclipse Che repository

src/api/kube.ts, src/commands/server/start.ts, src/installers/helm.ts
Mainly related to https://github.com/eclipse/che/issues/13801 which is 7.0.0 related
needs to be merged with https://github.com/eclipse/che/pull/13812
=> fix(helm): fix helm related errors

README.md
Reported with PR comments there: https://github.com/che-incubator/chectl/pull/228
=> docs(README): Add description about PR checks

.github/PULL_REQUEST_TEMPLATE.md
It fixes https://github.com/eclipse/che/issues/13933
Change-Id: Icba503c59a3549e87c50a3e8967b841dfa1c741e
=> chore(github): Update pull request templates

README.md
Update README with latest automatic changes
Probably need to check if README is modified in PR check to avoid merging PR without README.MD changes
Change-Id: Id53ea7000641e9aea22795b1c8de5d823a831f55
=> docs(README): when we committed changes we didn't push README.MD changes

README.md
add new install instructions for chectl
Related to https://github.com/eclipse/che/issues/14114
Change-Id: I7617eda8b779b8f4d435139c5a2d27bdb32dd4b4
=> docs(README): add new install instructions for chectl

README.md, src/commands/server/start.ts, src/platforms/minishift.ts, src/platforms/openshift.ts
Do ask for domain parameter for openshift/minishift platforms
This PR is under WIP phase because it is supposed to be merged in 7.1.0
N/A
=> fix(openshift/minishift): Do ask for domain parameter for openshift/minishift platforms

src/api/kube.ts
fix catching of errors
It does not really solve https://github.com/eclipse/che/issues/14303 but helps to get a cause of failing
=> fix(kube): fix catching of errors

src/commands/server/start.ts, src/platforms/crc.ts, test/platforms/crc.test.ts
It fixes https://github.com/eclipse/che/issues/13940
Change-Id: If172e3b88df6f36aad09c1d69bab76ef5616fd2e
=> feat(crc): Add support for CodeReady Containers

README.md, src/commands/server/start.ts
You may have minikube installed but maybe it's not where you want to use the cli tool.
Here it makes --platform parameter mandatory
#174
=> Always ask platform parameter. And not assume minikube is the default one.

.github/PULL_REQUEST_TEMPLATE.md, README.md
Signed-off-by: mikoto2000 <mikoto2000@gmail.com>
I fixed link break about CONTRIBUTING in README and PULL_REQUEST_TEMPLATE.
N/A
=> docs(CONTRIBUTING): fix link break about CONTRIBUTING.

src/installers/helm.ts
Signed-off-by: mikoto2000 <mikoto2000@gmail.com>
I fixed error message of self signed cert not found error.
Create self signed cert(`ca.crt`) is need `generic` type.
N/A
=> fix(helm): fix error message of self signed cert.

README.md
Keep README file up-to-date
Change-Id: Idad4465357511f057cd02b6af15ecf0c62cc3a8c
=> docs(README): Keep in sync README with current help

make-release.sh
Fixes a couple of typos and remove a commented line
N/A
=> chore(release): minor fixes to make-release.sh

README.md
fix eclipse/che/issues/14432
Signed-off-by: Fabrice Flore-Thébault <ffloreth@redhat.com>
=> docs(README): Clarify when the next channel is updated

package.json, src/api/che.ts, src/api/kube.ts, src/commands/devfile/generate.ts, src/commands/workspace/inject.ts, src/tasks/installers/helm.ts, src/tasks/platforms/crc.ts, test/api/che.test.ts, yarn.lock
Bump Kubernetes client library
Lot of API breaking changes, so had to update many lines
https://github.com/che-incubator/chectl/pull/180 
Change-Id: I94ac16de37509b303aa259a35f4d82b631f11265
=> feat(k8s): Bump the 3rd party library to communicate with Kubernetes 0.10.2

src/tasks/che.ts
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
=> Fix typo retreive -> retrieve eclipse/che#14808

package.json, src/tasks/installers/helm.ts, src/tasks/installers/minishift-addon.ts, src/tasks/installers/operator.ts, yarn.lock
Replace `ncp` with `fs-extra.copy`, since the first one is not designed to be used with Promises.
This issue was found while working on https://github.com/eclipse/che/issues/14793
In my draft ncp was not stable, and then I discovered that it works in other places because there are some extra steps between copying and reading files, like Create namespace https://github.com/che-incubator/chectl/blob/master/src/tasks/installers/operator.ts#L47
=> fix: fix copying of directories

make-release.sh, src/api/kube.ts, src/commands/server/start.ts, src/commands/server/update.ts, src/constants.ts
This back ports the fix added in #383 
#383
=> Back-port #383

make-release.sh
Update the release script to be consistent with current release flow:
- create upstream version branch (e.g. `7.4.x`) based on master branch
- change versions in source code and commit
- create a PR to update upstream version branch
- merge PR and push to `release` branch (not automated)
N/A
=> chore(release): update release script

src/common-flags.ts
Fix wording
https://github.com/redhat-developer/codeready-workspaces-chectl/pull/9/files
=> fix(flag): Typo/wording

src/common-flags.ts
backport #389 on 7.3.x as suggested by @ibuziuk
=> Backport fix typo

package.json, yarn.lock
Keep dependencies up-to-date (direct/indirect) by regenerating yarn.lock
N/A
Change-Id: I709281f3af9862b478c3ca9124ebef8b2b8d5219
=> feat(dependencies): Keep dependencies up-to-date

README.md
Update README (automatically generated)
=> fix(README): Keep README up-to-date

src/commands/server/start.ts
Signed-off-by: Tom George <tg82490@gmail.com>
Allows you to install che with OpenShift OAuth enabled on crc
eclipse/che#15108
=> Add crc as a platform that will install with openshift oauth

src/commands/server/start.ts
Signed-off-by: Tom George <tg82490@gmail.com>
Backports https://github.com/che-incubator/chectl/pull/406 to 7.3.x
https://github.com/eclipse/che/issues/15108
=> fix: Add crc as a platform that will install with openshift oauth

README.md, src/api/che.ts, src/commands/server/logs.ts, src/commands/workspace/logs.ts, src/commands/workspace/start.ts, src/tasks/che.ts, yarn.lock
Fix `workspace:create` command.
https://github.com/eclipse/che/issues/15578
=> fix: Fix workspace:create command

RELEASE.md, make-release.sh
Update the release script and add a REALEASE.md file with the steps to do a release of chectl.
https://github.com/eclipse/che/issues/15506
=> chore(release): update release script and add RELEASE.md

README.md, make-release.sh, src/constants.ts, test/api/replies/get-deployment-che-available.json, test/api/replies/get-deployment-che-progressing.json, test/api/replies/get-deployment-che-running.json, test/api/replies/get-pod-by-selector-pending.json, test/api/replies/get-pod-by-selector-ready.json, test/api/replies/get-pod-by-selector-running-ready.json, test/api/replies/get-pod-by-selector-running.json, test/api/replies/get-pods-che-running.json, test/tasks/installers/minishift-addon.test.ts, yarn.lock
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>
Move to quay.io: change image id
=> Move to quay.io: change image id

src/api/che.ts, src/commands/devfile/generate.ts, src/commands/server/delete.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts, src/common-flags.ts, src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/installers/operator.ts, test/api/che.test.ts, test/commands/server/start.test.ts, test/commands/server/stop.test.ts
Rename or remove some of Eclipse Che lables to optimize its synchronization with downstream (by autoreplacement of those labels)
=> Cleanup inconsistent labeling of Eclipse Che

README.md
keep doc up-to-date
N/A
Change-Id: I0ead486ae8588df0dc2f2b77aba4e4aee5772434
=> fix(doc): Update README after using yarn pack command that generates README.md

README.md, src/api/kube.ts, src/commands/server/debug.ts, src/commands/server/start.ts, src/commands/workspace/start.ts, src/tasks/che.ts, src/tasks/installers/helm.ts, yarn.lock
Introduce `server:debug` commands with is basically starts forward port to debug Eclipse Che server locally.
https://github.com/eclipse/che/issues/14976
=> feat: Allow to debug Eclipse Che Server locally

.github/CODEOWNERS
Update the code owners to match new teams
N/A
Change-Id: I948e52030533e077e550463b41b072da68b86416
=> chore(github): Update code owners to match new teams

src/api/che.ts, src/api/kube.ts, yarn.lock
Use watch utility to monitor newly created pods and start collecting logs from containers.
https://github.com/eclipse/che/issues/15986
=> fix: Use watch utility to monitor newly created pods

README.md, src/commands/server/delete.ts, yarn.lock
Add confirmation to delete Eclipse Che server
`You're going to remove Eclipse Che server in namespace 'che' on server 'https://192.168.99.100:8443'. If you want to continue - press Y:`
https://github.com/eclipse/che/issues/16000
=> feat: Add confirmation before deleting Che server

src/commands/server/delete.ts, yarn.lock
Fix namespace where server will be deleted
=> fix: Fix namespace where server will be deleted

src/tasks/che.ts, yarn.lock
Collects operator logs during installation
https://github.com/eclipse/che/issues/16073
=> feat: Collect operator logs

src/tasks/che.ts
Fix link explaining how obtain access token
https://github.com/eclipse/che/issues/16132
=> fix: Fix doc link

src/api/kube.ts, yarn.lock
Fix import
https://github.com/eclipse/che/issues/16139
=> fix: Fix import

src/commands/server/start.ts, yarn.lock
Fix tls by default for helm
https://github.com/eclipse/che/issues/16168
=> fix: Fix tls by default

src/tasks/installers/operator.ts, yarn.lock
Fix errors on post flight checks when used external postgress or devfile, plugin registries
https://github.com/eclipse/che/issues/15601
https://github.com/eclipse/che/issues/15496
=> fix: Fix errors on post flight checks when used external postgress or devfile, plugin registries

README.md, src/commands/server/delete.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/installers/minishift-addon.ts
=> fix: Some fixes for crwctl

README.md, yarn.lock
=> fix: Update README.md

.ci/cico_chectl_prcheck.sh, .ci/cico_common.sh, .ci/start-minikube.sh, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts
Create minikube cluster in ci.centos.org and run broken e2e tests.
=> fix: Fix basic e2e tests in minikube and minishift

src/tasks/installers/installer.ts, src/tasks/platforms/platform.ts
reorder if blocks in platform and installer so we can more easily exclude them when converting code into crwctl version
Change-Id: I4f262d9baf1b3e129c646f958ebb137a3916276a
=> feat: reorder if blocks in platform and installer so we can more easily exclude them from crwctl

.ci/cico_chectl_prcheck.sh, .ci/cico_common.sh, test/e2e/minishift.test.ts
Add GITHUB_TOKEN to minishift installation
=> fix: Add github token to minishift installation

src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/platforms/platform.ts, yarn.lock
reorder if blocks in platform and installer so we can more easily exclude them when converting code into crwctl version
/cc @nickboldt
=> feat: reorder if blocks in platform and installer and use correct selectors

README.md, src/api/che.ts, src/commands/workspace/start.ts, test/api/che.test.ts
Removes ability to create a workspace from a config
https://github.com/eclipse/che/issues/15061
=> fix: Remove ability to create a workspace from a config

.travis.yml
This PR will add support for s390x.
=> feat: Add s390x Support for Travis

_layouts/stable-channel.html, _layouts/stable-download-link.html
Temporary fix release page for stable channel
=> fix: Fix release pages

src/commands/server/start.ts, src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/installers/operator.ts
Support deploying in single user mode with operator
https://github.com/eclipse/che/issues/13420
https://github.com/eclipse/che-operator/pull/185
=> feat: Support deploying in single user mode with operator

devfile.yaml
Fix workspace start with chectl devfile
none
=> fix: Fix dev image in the devfile.

devfile.yaml
Optimize minimum RAM for devfile. Add debug config to debug from /projects
=> fix: Optimize minimum RAM for devfile. Add debug config.

README.md
Updates readme for `workspace:start` and `workspace:create` commands according to changes in https://github.com/che-incubator/chectl/pull/592
=> docs: Update readme for workspace:start and workspace:create commands

_includes/last-stable-release.html, _layouts/stable-channel.html, _layouts/stable-download-link.html
Fix missing gz link for stable channel
=> fix: Fix missing gz link for stable channel

.travis.yml
=> fix: Fix duplicated releases

RELEASE.md, make-release.sh
Simplify release process, removes some manual steps.
=> feat: Improve release script

.ci/che-cert_generation.sh, .ci/cico_chectl_prcheck.sh, .ci/cico_common.sh, .ci/start-minikube.sh, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts
This PR add certificates to e2e tests to tests chectl startup on minikube and minishift.
=> fix: Fix e2e tests by adding certificates

src/tasks/platforms/common-platform-tasks.ts, yarn.lock
=> fix: Temporarily remove cluster check

make-release.sh
Correct replacing tags for images in `src/constants.ts` in case of bugfix releases.
=> fix: Fix make-release.sh

.ci/start-minikube.sh
This Pull request update minikube version to 1.8.2 and kubernetes version 1.16.2
=> fix: Update minikube version

.ci/cico_chectl_minikube.sh, .ci/cico_chectl_minishift.sh, .ci/start-minikube.sh
This PR add ability to separate e2e tests by platform(minikube and minishift). More info in Ref. issue.
https://github.com/eclipse/che/issues/16932
=> feat: Add scripts to separate e2e tests for chectl

.travis.yml
This PR change os jobs from OSX to linux and add the latest stable version of nodejs.
https://github.com/eclipse/che/issues/16801
=> fix: Change OS and nodejs version

.travis.yml
This PR add support for macos and windows arch.
=> fix: Add support for windows and macos on linux travis ci job

.travis.yml
Revert latest changes of travis CI.
=> fix: Revert travis ci changes

src/commands/server/start.ts, src/tasks/installers/helm.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, src/util.ts, yarn.lock
Improves some warn messages
https://github.com/eclipse/che/issues/16968
=> fix(messages): Improve warn messages

src/api/kube.ts, src/commands/server/update.ts, src/constants.ts, src/tasks/installers/installer.ts, src/tasks/installers/olm.ts
Improve OLM installer to re-use in the CodeReady.
https://github.com/eclipse/che/issues/16862
=> fix: Improve OLM installer to re-use in the CodeReady

package.json, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts
Add more logs and command for e2e.
none. Development enhancements
=> fix: Add more logs and commands for e2e.

.travis.yml
Signed-off-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>
This PR will add support for ppc64le.
=> feat: Add ppc64le support on travis-ci

src/commands/server/start.ts
Add missed await for olm preinstallation check.
https://issues.redhat.com/browse/CRW-967
=> fix: Add missed await for olm preinstallation check.

src/tasks/installers/installer.ts
Fix typo "installaion" in output message.
=> fix: typo "installaion" in output message.

yarn.lock
https://github.com/eclipse/che/issues/16815
Update operator templates.
=> chore(yarn.lock): Update operator templates.

.ci/cico_chectl_openshift.sh, .ci/openshift-ci/Dockerfile, test/e2e/openshift.test.ts
This PR create e2e test for openshift platform 4.X and add ci scripts to execute in openshift CI testing platform.
=> feat: Create e2e tests for openshift 4.X platform

.ci/cico_chectl_minikube.sh, .ci/cico_chectl_minishift.sh, .ci/cico_chectl_openshift.sh
This PR add improvement to collect logs of deployments in case of error
=> fix: Collect logs in centos ci in case of error

src/commands/server/start.ts, src/commands/server/update.ts, yarn.lock
Mention platform in installer description
https://github.com/eclipse/che/issues/17165
=> fix: Mention platform in installer description

src/api/che.ts, src/commands/workspace/delete.ts, yarn.lock
Print meaningful error message when user tries to delete a running workspace
https://github.com/eclipse/che/issues/17270
https://issues.redhat.com/browse/CRW-1017
=> chore: Print meaningful error message when user tries to delete a running workspace

src/commands/server/delete.ts
Fix notification
https://github.com/eclipse/che/issues/17688
=> fix: Fix notification for server:delete command

.vscode/launch.json, src/api/kube.ts, src/tasks/installers/operator.ts
This PR  check if CRD are up to date verifying the number of properties and check CRD versions. 
This Pr also create cluster roles and role binding using namespace name..
https://github.com/eclipse/che/issues/14419
=> feat: Ensure CRD are up to date and create cluster roles and cluster role binding using namespace unique name

README.md, src/common-flags.ts, src/constants.ts, src/tasks/che.ts
Adds doc links explaining how to obtain access token.
https://issues.redhat.com/browse/CRW-803
=> fix: Add doc link how to obtain access token

src/commands/server/start.ts, src/constants.ts, yarn.lock
Fix docs link after changes in che-doc repository
=> fix: doc links

yarn.lock
Adds changes in Helm chart template from https://github.com/eclipse/che/pull/17773 into chectl.
https://github.com/eclipse/che/issues/17766
=> chore(deps): Apply new Helm chart templates

README.md, src/constants.ts
=> chore: Fix docs link

README.md, src/api/typings/olm.d.ts, src/commands/server/start.ts, src/constants.ts, src/tasks/installers/olm.ts, src/util.ts, yarn.lock
Use nightly olm channel.
https://github.com/eclipse/che/issues/17183
https://github.com/eclipse/che-operator/pull/423
=> feat: Use nightly olm channel.

.github/CODEOWNERS
=> feat: Add flacatus to codeowner

yarn.lock
Update dependencies
https://github.com/eclipse/che/issues/17888
=> chore: Update dependencies

src/commands/server/start.ts
Update property due to comment in PR
https://github.com/che-incubator/chectl/pull/862#discussion_r491922760
Change-Id: I9a4bbcdd1825108b2f667bca975bc2b91fba9f04
=> fix: property name was subjective

src/api/kube.ts, yarn.lock
Adopt kube.ts after changing client-node version
https://github.com/eclipse/che/issues/17919
=> fix(kube.ts): Adopt kube.ts after changing client-node version

src/api/che.ts, src/tasks/che.ts
[Here](https://github.com/che-incubator/chectl/pull/849) some methods were deprecated. This PR deletes deprecated methods and replaces their usages in other places.
https://github.com/che-incubator/chectl/pull/849
=> refactor(che helper): Delete deprecated methods

src/api/kube.ts
Adopt kube.ts after changing client-node version
https://github.com/eclipse/che/issues/17976
=> fix: Adopt kube.ts after chagning client-node version (#879)

src/commands/cacert/export.ts, src/commands/dashboard/open.ts, src/commands/devfile/generate.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/create.ts, src/commands/workspace/delete.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/logs.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts
fix: add explicit flag type annotations per https://github.com/microsoft/TypeScript/issues/29221 to fix downstream build
Change-Id: I9eee44451b2ed41382cda9a446c47fc5c8f39e33
=> fix: add explicit flag type annotations per microsoft/TypeScript#29221 to fix downstream build

.gitignore, .vscode/tasks.json
Improve dev flow: add often used commands to use them them from IDE instead of type them each time.
None
Launch dev command using VSCode. Click `Terminal` from main bar, click `Run task...`, select desired command from popup and click. IDE should launch command. To edit command use configure button on the popup or open .vscode/tasks.json.
=> feat: Add dev commands.

.gitignore, README.md, src/api/kube.ts, src/tasks/che.ts, src/tasks/installers/operator.ts, src/tasks/kube.ts, test/api/kube.test.ts
PR adds check on downloading and staring images to fail immediately and don't wait 2m timeout
❯ Operator pod bootstrap
✔ Scheduling...done.
✖ Downloading images...failed
→ Failed to download image: rpc error: code = Unknown desc = Error response from daemon: pull access denied for test, repository does not exist or may require 'do
❯ Operator pod bootstrap
✔ Scheduling...done.
✔ Downloading images...done.
✖ Starting...failed
→ Failed to start container(s): back-off 10s restarting failed container=che-operator pod=che-operator-756f87dbc-z5knk_che(fe6e4cc9-1349-4a0a-85b7-0a69f56fcde6)
https://github.com/eclipse/che/issues/17942
https://github.com/eclipse/che/issues/17937
1. Build sources
2. `bin/run server:start --platform minikube …
=> feat: Detects issues with downloading images and starting containers

.vscode/launch.json, .vscode/tasks.json, README.md, src/commands/server/deploy.ts, src/commands/server/update.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, test/e2e/openshift.test.ts
Back port changes https://github.com/che-incubator/chectl/pull/909
=> Deprecate server:start command

src/api/kube.ts, src/api/typings/olm.d.ts, src/tasks/installers/olm.ts
Make it possible to specify custom operator image in case of OLM installer
https://github.com/eclipse/che/issues/17936
```
chectl server:start --platform=openshift --installer=olm --che-operator-image=<your-custom-image>
```
Then check `image` field in operator pod
=> Respect '--che-operator-image' parameter by OLM installer

src/commands/server/deploy.ts
Back port to branch 7.20.x: Fix appearing `serverstart` command deprecation note
Little quick fix
Run:
```
./bin/run server:deploy -n che -p openshift -m
```
Message:
`Warning: 'server:start' command is deprecated. Use 'server:deploy' `
should not appear.
=> fix: Back port to branch 7.20.x. Fix server start deprecation note appearing

README.md
Update README.md file
none.
Not needed. Update for docs
=> fix: Update README.md file

src/api/kube.ts, src/tasks/component-installers/cert-manager.ts, src/tasks/installers/common-tasks.ts, yarn.lock
Don't print import certificate message in single-host mode
https://github.com/eclipse/che/issues/18082
=> fix: Don't print import certificate message in single-host mode

src/api/che-login-manager.ts, src/tasks/che.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, test/e2e/openshift.test.ts, test/e2e/util/e2e.ts
Prints correct error message if only access token without API URL is provided for a command that requires login.
Run
```
chectl workspace:start some-id --access-token=test
```
=> fix: Improve error message for case when access token provided without Che server URL

src/api/che.ts, src/tasks/installers/common-tasks.ts
Fixes displaying keycloak credentials after deploying Eclipse Che
```
✔ Identity Provider URL     : https://<host>/auth
✔ Identity Provider login   : "admin:admin".
```
1. Build
2. Deploy Eclipse Che
3. Check the output
=> fix: Display keycloak credentials

README.md, src/api/kube.ts, src/commands/server/deploy.ts, src/tasks/installers/helm.ts
Adds new option `--helm-patch-yaml` to be able to provide amendment for Helm Chart values from chectl.
N/A
Create a file `helm-patch.yaml` with content like:
```yaml
global:
workspaceIdleTimeout: "1800000"
tls:
enabled: true
secretName: che-tls
pvcClaim: "1Gi"
cheImage: quay.io/che-server:latest
che-keycloak:
image: quay.io/eclipse/che-keycloak:nightly
requireAdminPasswordChange: false
```
Then run:
```
chectl server:deploy --platfrom=minikube --installer=helm --multiuser --helm-patch-yaml=helm-patch.yaml
```
=> Add --helm-patch option

src/commands/server/update.ts
Fix usage `--yes` flag on server:update command
1. Build project
2. Deploy Eclipse Che
3. Use `server:update` with `--yes` flag. chectl will update Eclipse Che in non interactive mode.
=> fix: Fix yes flag usage

src/commands/server/deploy.ts
I found a gap in my codebase. Actually suggested namespace and setPlaformDefaults() function are set it after instance `cheTasks(flags)` class.
Ref issue: https://github.com/eclipse/che/issues/18411
=> fix: Fix olm-suggested-namespace gap

yarn.lock
Signed-off-by: svor <vsvydenk@redhat.com>
Bumps [eclipse-che-operator](https://github.com/eclipse/che-operator) from `bfdc529f` to `2e0bfec`.
https://github.com/eclipse/che/issues/17205
=> feat: Bump eclipse-che-operator

src/tasks/installers/helm.ts
Remove `-skip-refresh` flag from `helm dependencies update` command. Seems using this flag with newer helm version the installation fails with error: Command failed with exit code 1: helm dependencies update --skip-refresh /home/flacatus/.cache/chectl/templates/kubernetes/helm/che/
I tested removing this flag with helm 2.X and I install successfully Che.
Ref issue: https://github.com/eclipse/che/issues/18396
=> fix: remove --skip-refresh flag from helm dependencies update

src/api/kube.ts, src/tasks/installers/operator.ts, yarn.lock
Signed-off-by: Michal Vala <mvala@redhat.com>
after https://github.com/eclipse/che-operator/pull/543, we need to set correct namespace-editor clusterrole into CheCluster CR.
https://github.com/eclipse/che/issues/18400
1. deploy with operator
1. check that cheClusterRoles is set to valid clusterrole name
=> fix: set cheClusterRoles to correct clusterrole name

src/api/kube.ts
Set `namespaceEditorClusterRoleName` correctly.
=> fix: Set namespaceEditorClusterRoleName

.github/workflows/release.yml
Create release.yml for chectl release
https://github.com/eclipse/che/issues/17857
=> Create release.yml for chectl release (#17857)

yarn.lock
Update dependencies after https://github.com/eclipse/che-operator/pull/541
=> chore(yarn.lock): Update che-operator dependencies

yarn.lock
Update eclipse/che dependency after https://github.com/eclipse/che/pull/18574
https://github.com/eclipse/che/issues/18499
=> chore(yarn.lock): Update eclipse/che dependency

src/util.ts, tsconfig.json
Fix issue with importing package.json
=> Fix issue with importing package.json

test/e2e/e2e.test.ts, test/e2e/util.ts
Remove timeout from workspace:list and add execa for server:delete tests... For all tests it is using execa to execute chectl commands.
=> fix: Fix timeout and add execa for server:delete e2e tests

.github/workflows/release-build-and-push-to-GH-releases.yml
Change release regexp branch in job to avoid create multiple releases:
Example: Right now we are creating stable release and we are creating 2 branch one is 7.23.x and another one is 7.23.0... Changing regexp branch to 7.*.x will trigger the release job only in one branch
=> fix: Improve branch regexp in release job

test/e2e/resources/helm-patch.yaml
Since https://github.com/eclipse/che/pull/18707/files#diff-f42e80a862837c141fdd7db127b4509552f6379ff651fa9dd6cfcd31b5e21eabR51 helm e2e tests are broken. The problem should be fixed by adding:
global:
useInternalClusterSVCNames: false
=> fix: [HELM] Fix e2e tests

src/tasks/installers/helm.ts
Fix typo which allows to observer keycloak pod bootstrap.
1. Build
2. Deploy using `--installer helm`
3. See keycloak pod bootstrap
=> Fix typo in keycloak deployment

.github/workflows/automation-check.yml
Add workflow which check if Readme file it is up to date.
Ref. issue: https://github.com/eclipse/che/issues/18294
=> feat: Add automation check for readme file

devfile.yaml
Fix devfile
none
Create new workspace from devfile.
=> fix: Fix devfile.

.github/workflows/codecov.yml, README.md, package.json, test/e2e/e2e.test.ts, test/e2e/resources/devfile-example.yaml, test/e2e/util.ts
Replace empty devfile with quarkus devfile official
Reff issue: https://github.com/eclipse/che/issues/18767
=> feat: Add quarkus devfile to e2e tests and rename codecov.yml workflow

.github/workflows/e2e-minishift-operator.yml, src/hooks/analytics/analytics.ts
=> fix: Change telemetry command line message

.github/workflows/e2e-minishift-operator.yml, src/hooks/analytics/analytics.ts
=> fix: [BACKPORT] Change telemetry command line message

.github/workflows/happy-path.yml
Add happy path tests to release branches.
=> feat: Add happy path tests for release branches

src/tasks/che.ts, src/tasks/installers/helm.ts
Removes PVSs of Che Keycloak when deleting Che.
Fixes https://github.com/eclipse/che/issues/18276
1. Deploy Eclipse Che: `chectl server:deploy --platform=minikube --installer=helm --multiuser`
2. Delete Eclipse Che: `chectl server:delete -y`
3. Check that Che Keycloak's PVS are gone: `kubectl get pvc -A`
=> fix: Remove Eclipse Che keycloak's PVCs on server:delete

.github/workflows/happy-path.yml
In order to see possible problems with happy path this pr upload all e2e artifacts to GH actions
=> fix: Upload happy path tests artifacts to GH actions

yarn.lock
Update templates.
Needed for https://github.com/eclipse/che/issues/15493 to update che-operator templates.
=> chore(package.json): Update templates.

src/api/che.ts, src/constants.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/operator.ts, yarn.lock
Move che-operator template dir to const to replace correctly in downstream project.
=> chore: Move che-operator template dir to const

yarn.lock
Update templates.
https://github.com/eclipse/che/issues/18152
=> chore: Update templates.

src/hooks/prerun/new-version-warning.ts
Update the list of chectl commands that shouldn't have the update warning appear.
N/A, feedback from users
Run `chectl update` command on an older version of chectl. The warning shouldn't be printed.
=> Update print-no-update-warning commands list

package.json
=> Change devworkspace operator branch from master to main

install.sh
Fix chectl installation in some environment where `declare -F` display some functions with no NAMEs export. (`declare -f functioname` instead of `declare -fx functionname`)
N/A
https://github.com/eclipse/che/issues/19135
Just make sure that the script is still working. This is a corner case in some environment.
=> fix(installer-exec): declare should ignore some functions with no NAMEs export

.github/workflows/e2e-minikube-operator-assembly.yml, test/e2e/e2e.test.ts
Refference issue: https://github.com/eclipse/che/issues/19026
=> feat: Add assembly tests for chectl to test production binaries

.github/workflows/release-stable-PRs.yml, make-release.sh
Add ability to specify release version of DevWorkspace Operator when doing Chectl release.
=> Use release versions of DWO in releases

yarn.lock
Updates dependencies after https://github.com/eclipse/che-operator/pull/689
=> chore(yarn.lock): Update dependencies

.github/workflows/e2e-minikube-helm.yml, .github/workflows/e2e-minikube-olm.yml, .github/workflows/e2e-minikube-operator-assembly.yml, .github/workflows/e2e-minikube-operator-update.yml, .github/workflows/e2e-minikube-operator.yml, .github/workflows/e2e-minishift-operator.yml, .github/workflows/happy-path.yml, README.md, src/api/che.ts, src/commands/workspace/logs.ts, src/common-flags.ts, test/e2e/e2e-upgrade.test.ts, test/e2e/e2e.test.ts, test/e2e/util.ts
Collect workspace logs in e2e tests.
Also add ability to workspace:logs to stream logs or not by addon --follow flag.
Reff issue: https://github.com/eclipse/che/issues/19213
=> Grab e2e Che logs in GH actions artifacts and allow workspace:logs to stream or not the logs

.github/workflows/release-build-and-push-to-GH-releases.yml
Change-Id:...
add MM message
Change-Id: I160e17a0bc46ddb3d1bdd7e3f48b246a28abf893
N/A
https://github.com/eclipse/che/issues/18906#issuecomment-796472177
N/A
=> feat: add MM message

.github/workflows/release-stable-PRs.yml
Fix a typo in the release script
=> Fix make-release.sh invocation during release

src/tasks/component-installers/devfile-workspace-operator-installer.ts
Fix yaml name of workspaceRouting for devworkspace operator
=> Fix dwo CRD file name

src/tasks/component-installers/devfile-workspace-operator-installer.ts
PR https://github.com/devfile/devworkspace-operator/pull/336 removes the Component CRD from the DevWorkspace Operator. As a result, depending on the components file will cause issues going forward in chectl, and it should be removed.
No issue created yet, but we'll see failures soon as https://github.com/devfile/devworkspace-operator/pull/336 is merged to main
- [n/a] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [n/a] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- …
=> Remove Components CRD from devworkspace operator deployment

src/api/github-client.ts, test/e2e/e2e-upgrade.test.ts, test/e2e/util.ts
1. Increase workspace creation timeout
2. In case of release read VERSION file to get latest release version and update
Ref. issue: https://github.com/eclipse/che/issues/19212
=> fix: Run update tests in release process

.github/workflows/release-build-and-push-to-GH-releases.yml, .github/workflows/release-stable-PRs.yml
- send notifications during the creation of Chectl PRs
- add an option to regenerate tags before the release
=> Improve release script

.ci/openshift-ci/Dockerfile
=> Fix openshift ci Dockerfile `from`  name and add node 12.x version for tests

src/api/che-login-manager.ts, src/commands/auth/login.ts
Detect working namespace for auth:login command
1. Deploy Eclipse Che on minikube
2. Try `chectl auth:login -u admin -p admin`
3. User successfully logged in
=> fix: Detect working namespace for auth:login command

src/api/kube.ts, src/tasks/che.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, test/e2e/e2e.test.ts
`server:delete` should n't fail if resource not found
https://github.com/eclipse/che/issues/19241
1. Deploy Eclipse Che 
2. Run `server:delete`  twice
=> fix: Don't fail if resource doesn't exist

.github/workflows/release-build-and-push-to-GH-releases.yml
Update GitHub pages after release is done
https://github.com/eclipse/che/issues/19321
=> Update GitHub pages after release is done

src/api/version.ts
Don't fail if latest chectl version is unknown
https://github.com/eclipse/che/issues/19165
=> fix: Don't fail if latest chectl version is unknown

README.md, src/api/kube.ts, src/commands/server/deploy.ts, src/constants.ts, src/tasks/che.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, test/e2e/e2e.test.ts
=> feat: Backport dwo installation removal after delegate in che operator .

.github/workflows/codecov.yml, .github/workflows/e2e-minikube-devworkspace.yml, .github/workflows/e2e-minikube-helm.yml, .github/workflows/e2e-minikube-olm.yml, .github/workflows/e2e-minikube-operator-assembly.yml, .github/workflows/e2e-minikube-operator-update.yml, .github/workflows/e2e-minikube-operator.yml
Switches to minikube 1.18.1 in GitHub actions while eclipse/che#19602 isn't fixed.
=> fix: Install minikube 1.18.1 instead of latest one

src/tasks/che.ts
Credentials secret for initial OpenShift OAuth is are put into `openshift-config` namespace.
`chectl` should respect both legacy and a new behaviors 
https://github.com/eclipse/che/issues/19380
=> Read secret from openshift-config namespace to print credentials

src/api/kube.ts, src/tasks/installers/operator.ts
OCP 3.11 is supposed to use a different operator deployment (without DWCO specific things)
So, for OCP 3.11 we will keep the only one container names as `che-operator` and remove others.
https://issues.redhat.com/browse/CRW-1720
=> feat: Use OCP 3.11 specific operator deployment

src/api/kube.ts
https://issues.redhat.com/browse/CRW-1720
Fix check API version support
=> fix: Fix check API version support

.github/workflows/e2e-minikube-olm.yml
Installs stable olm v0.17.0 for tests in GitHub actions
=> fix: Installs stable olm v0.17.0 for tests in GitHub actions

.github/workflows/e2e-minishift-operator.yml, yarn.lock
Update operator dependencies after https://github.com/eclipse-che/che-operator/pull/794
Reff issue: https://github.com/eclipse/che/issues/19454
=> Update operator dependencies

src/tasks/installers/operator.ts
Creates and updates the crd needed for DWCO if k8s supports `apiextensions.k8s.io/v1` api:
- chemanagers.che.eclipse.org.CustomResourceDefinition.yaml  
- devworkspaceroutings.controller.devfile.io.CustomResourceDefinition.yaml
N/A
https://github.com/eclipse/che/issues/19402
N/A
=> fix: Manage CRD needed for DWCO

.github/workflows/e2e-minikube-devworkspace.yml, .github/workflows/e2e-minikube-helm.yml, .github/workflows/e2e-minikube-olm.yml, .github/workflows/e2e-minikube-operator-assembly.yml, .github/workflows/e2e-minikube-operator-update.yml, .github/workflows/e2e-minikube-operator.yml, .github/workflows/happy-path.yml
Use che-incubator/setup-minikube-action to start a minikube cluster
N/A
N/A
N/A
=> fix: Use che-incubator/setup-minikube-action to start a minikube cluster

src/tasks/che.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/helm.ts
This PR propagate Dashboard Deployment startup, export logs, stop on server:stop
Reff issue: https://github.com/eclipse/che/issues/19605
N/A 
N/A 
=> feat: Respect new Eclipse Che Dashboard  deployment

.github/workflows/happy-path.yml
Fix happy path action
N/A
N/A
N/A
=> fix: happy path action

yarn.lock
Right now it is not possible to deploy Eclipse Che nightly because templates are not up-to-date after: https://github.com/eclipse-che/che-operator/pull/815
https://github.com/eclipse/che/issues/19773
N/A
N/A
N/A
=> fix: Update chectl templates

src/tasks/installers/operator.ts
When installing on OCP 3.11, don't suggest to use OLM install mode
N/A
https://github.com/eclipse/che/issues/19777
1. Run tests on minishift, check that message is not appeared
=> fix: When installing on OCP 3.11, don't suggest to use OLM install mode

.github/workflows/release.yml
Use Che incubator bot GitHub token in release workflow (for consistency with other projects)
=> Use Che incubator bot github token for release

package.json, src/tasks/installers/operator.ts, src/util.ts, test/other/util.test.ts
Fixes update of Che from chectl in case when operator image registry has custom port.
N/A
Fixes https://github.com/eclipse/che/issues/19860
Try to update Che when operator image registry has port the reference, e.g. `registry.io:1234/account/image:tag`
=> Fix operator image name and tag parsing

src/api/github-client.ts
Fixes templates downloading for helmcharts from the correct repository
N/A
https://github.com/eclipse/che/issues/19915
`./run server:deploy --installer=helm --platform=minikube --version 7.31.0`
=> fix: downloading templates

src/tasks/installers/operator.ts
Uses `v1beta1` version for `CheClusterBackup` and `CheClusterRestore` CRDs in case of Openshift 3.x
N/A
https://github.com/eclipse-che/che-operator/pull/844
Deploy Eclipse Che on Openshift 3.x infrastructure with templates from https://github.com/eclipse-che/che-operator/pull/844
=> fix: Use CRDs of v1beta1 version on Openshift 3.x

make-release.sh
Correctly replaces dependency versions in package.json
N/A
https://github.com/eclipse/che/issues/19924
N/A
=> fix: Fix release process

src/tasks/installers/operator.ts
Fixes backup/restore CRDs creation
N/A
Hotfix for mistake in https://github.com/che-incubator/chectl/pull/1272
Deploy Eclipse Che with templates that don't have backup and restore CRDs
=> fix: Fix backup/restore CRDs creation

README.md, yarn.lock
=> build: Update dependency

src/tasks/installers/operator.ts, yarn.lock
chectl must not created of another controllers
N/A
https://github.com/eclipse/che/issues/19402
N/A
=> fix: chectl must not create CRDs of another controllers

src/tasks/component-installers/devfile-workspace-operator-installer.ts
This PR add a fix to remove completelly webhooks configurations when DWO will be uninstalled.
N/A
https://issues.redhat.com/browse/CRW-1930
N/A
=> fix: [Backport] Remove devworkspace validating webhook configuration from cluster if dwo will be uninstalled

yarn.lock
Updates reference to the newest version of operator templates.
Fixes https://github.com/eclipse/che/issues/20073
Deploy nightly Eclipse Che
=> Update yarn.lock to use the newest operator templates

test/e2e/util.ts, yarn.lock
Fixes e2e upgrade test
N/A
https://github.com/eclipse/che/issues/20086
1. Run `yarn test --coverage=false --forceExit --testRegex=test/e2e/e2e-upgrade.test.ts`
=> fix: e2e upgrade test

src/tasks/che.ts, src/util.ts
Add trailing slashes to printed urls
```
✔ Plug-in Registry          : https://plugin-registry-eclipse-che.192.168.99.100.nip.io/v3/
✔ Devfile Registry          : https://devfile-registry-eclipse-che.192.168.99.100.nip.io/
✔ Identity Provider URL     : https://keycloak-eclipse-che.192.168.99.100.nip.io/auth/
```
https://github.com/eclipse/che/issues/19995
N/A
=> chore: add trailing slashes to printed urls

src/api/kube.ts, yarn.lock
Correctly parse image if it contains ':'
N/A
https://github.com/eclipse/che/issues/19638
N/A
=> fix: correctly parse image if it contains ':'

.github/workflows/happy-path.yml
Update minikube version to v1.21.0 for happy-path tests
N/A
N/A
N/A
=> build: Update minikube version to v1.21.0

make-release.sh
Update eclipse-che/api dependency on release
N/A
N/A
N/A
=> build: Update eclipse-che/api dependency on release

yarn.lock
Update dependency
N/A
https://github.com/eclipse/che/issues/20162
N/A
=> chore(yarn.lock): Update dependency

.github/CODEOWNERS
Remove @l0rd  from codeowners
N/A
N/A
N/A
=> chore: Remove l0rd from codeowners

.github/workflows/release.yml, make-release.sh
Fix update of DWO version, that was removed by accident
=> fix: Fix release script updating DWO version

.vscode/tasks.json, src/api/kube.ts, src/constants.ts, src/tasks/installers/olm.ts, test/api/replies/get-deployment-che-available.json, test/api/replies/get-deployment-che-progressing.json, test/api/replies/get-deployment-che-running.json, test/api/replies/get-pods-che-running.json, test/api/version.test.ts, yarn.lock
Rename channel from nightly to next
N/A
https://github.com/eclipse/che/issues/20120
N/A
=> chore: Rename channel from nightly to next

src/api/che.ts, test/e2e/e2e-upgrade.test.ts, yarn.lock
Downloading templates from che-operator repository with a new project structure
N/A
https://github.com/eclipse/che/issues/20235
`./run server:deploy --platform minikube  --version 7.34.0`
=> fix: downloading templates from che-operator repository with a new project structure

.github/workflows/e2e-minikube-devworkspace.yml, src/commands/server/deploy.ts, test/e2e/e2e-upgrade.test.ts, test/e2e/e2e.test.ts
Deprecates helm installer
```
$ chectl server:deploy --platform minikube --installer helm
'helm' installer is deprecated. Do you want to proceed? [y/n]: 
```
https://github.com/eclipse/che/issues/20183
N/A
=> chore: deprecates helm installer

yarn.lock
Updates dependencies after https://github.com/eclipse-che/che-operator/pull/992
N/A
https://github.com/eclipse/che/issues/20182
N/A
=> build: Update dependencies

src/tasks/installers/olm.ts
When https://github.com/eclipse/che/issues/20118 is merged then `alm-examples` will contain several CRs.
This PR fixes finding CheCluster CR from `alm-examples` by its kind
N/A
https://github.com/eclipse/che/issues/20118
N/A
=> fix: find CheCluster CR from alm-examples by kind

src/commands/server/deploy.ts
If user type y, after notification about helm installer deprecation, then installation should start.
=> Fix helm installer confirmation.

README.md, src/commands/server/deploy.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/helm.ts, src/tasks/installers/installer.ts
Drops single-user mode
N/A
https://github.com/eclipse/che/issues/20315
N/A
=> chore: drop single-user mode

package.json, src/api/kube.ts, src/commands/devfile/generate.ts, yarn.lock
Use `networking/v1` api instead of `extensions/v1beta1`.
N/A
https://github.com/eclipse/che/issues/20431
Deploy Eclipse Che with chectl on minikube v1.23
=> Use networking/v1 api

package.json, src/hooks/analytics/segment-adapter.ts, yarn.lock
Bump countries-and-timezones to latest version to fix CRW-chectl sync scripts.
https://issues.redhat.com/browse/CRW-2261
=> fix: Upgrade countries and timezone dependency and fix typo

package.json, yarn.lock
This reverts commit 0ba9e364a7790c0809ce024603cb779c41f9df15.
Revert "chore(deps): Bump @kubernetes/client-node from 0.12.1 to 0.15.1
N/A
N/A
N/A
=> Revert "chore(deps): Bump @kubernetes/client-node from 0.12.1 to 0.15.1

src/commands/server/update.ts, test/e2e/e2e-upgrade.test.ts
Don't support downgrade Eclipse Che
N/A
https://github.com/eclipse/che/issues/20470
=> chore: don't support downgrade

src/constants.ts
Stable-all-Namespaces channel was renamed to `tech-preview-stable-all-namespaces`.
=> fix: Fix the name of stable-all-namespaces channel

src/constants.ts
Co-authored-by: Flavius Lacatusu <flacatus@redhat.com>
=> fix: Backport PR 1707 to fix channel naming

src/api/kube.ts, src/commands/server/update.ts, src/tasks/installers/olm.ts
backport: https://github.com/che-incubator/chectl/pull/1733
N/A
https://issues.redhat.com/browse/CRW-2320
N/A
=> fix: use operator namespace to find subscription

src/tasks/platforms/platform.ts
Fixes formatting by deleting redundant empty lines
N/A
N/A
N/A
=> chore: Fix formatting

src/constants.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts
Fix re-deploy Che via OLM installer.
https://issues.redhat.com/browse/CRW-2363
=> fix: BackPort 7.38.x fix re-deploy Che via OLM installer.

make-release.sh
After removing `eclipse-che/che-server` dependency we have to adapt the release process as well.
N/A
https://github.com/eclipse/che/issues/20739
N/A
=> chore: remove `eclipse-che/che-server` dependency from the release process

src/tasks/installers/installer.ts
fix: followup to https://github.com/che-incubator/chectl/pull/1787 - remove orphaned downstream annotation
Change-Id: Id0333904479f1aa1228b9a2702648c6d39904394
N/A
fix for incomplete solution in https://github.com/che-incubator/chectl/pull/1787
see also https://issues.redhat.com/browse/CRW-2455
N/A
=> fix: followup to #1787 - remove orphaned downstream annotation

.github/workflows/try-in-web-ide.yaml
Add try in Web IDE action
N/A
https://github.com/eclipse/che/issues/20664
N/A
=> ci: Add try in Web IDE action

src/api/kube.ts, src/constants.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, yarn.lock
* Update che-operator dependency and templates
* Make starting csv customizable (for downstream)
* Fix starting csv for `tech-preview-stable-all-namespaces` channel
https://issues.redhat.com/browse/CRW-1497
N/A
=> fix: Make starting csv customizable

.vscode/tasks.json, src/tasks/installers/operator.ts
Don't allow 'devworkspace' engine update for previous installations with 'che-server' engine.
https://github.com/eclipse/che/issues/20865
=> feat: Don't allow 'devworkspace' engine update for previous installations with 'che-server' engine.

src/api/backup-restore.ts
Takes into account backup server configurations only from the namespace where Che is installed
N/A
N/A
1. Create a backup
2. Create two backup server configurations: one in Che namespace, the other in a different namespace 
3. Run `chectl server:restore --snapshot-id=latest` 
chectl should pick up the right configuration
=> Look for backup server configurations only in Che namespace

src/tasks/platforms/minikube.ts
Wait untill nginx controller pod is ready
N/A
https://github.com/eclipse/che/issues/20888
N/A
=> fix: Wait untill nginx controller pod is ready

README.md, src/api/kube.ts, src/commands/server/deploy.ts, src/tasks/che.ts, src/tasks/installers/operator.ts, src/util.ts, test/e2e/e2e-rollback.test.ts, test/e2e/e2e-upgrade.test.ts, test/e2e/e2e.test.ts
Deploy Dev Workspace engine by default
N/A
https://github.com/eclipse/che/issues/20866
N/A
=> Deploy Dev Workspace engine by default

yarn.lock
Update che-operator dependency
N/A
N/A
N/A
=> ci: Update che-operator dependency

src/api/context.ts, src/api/kube.ts, src/api/types/olm.ts, src/commands/server/delete.ts, src/commands/server/deploy.ts, src/commands/server/restore.ts, src/constants.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts, src/tasks/installers/installer.ts, src/tasks/installers/olm-dev-workspace-operator.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, test/e2e/e2e.test.ts
* Install Dev Workspace next version from a custom catalog source if Eclipse Che is going to be deployed from the `next` channel
* Install Dev Workspace stable version from a custom catalog source if Eclipse Che is going to be deployed from the `stable` 
N/A
https://github.com/eclipse/che/issues/20908
https://github.com/eclipse/che/issues/20899
PRs checks
=> feat: Install next dev-workspace operator for all-namespaces next channel

.github/CODEOWNERS
=> Delete mmorhun from code owners

README.md, package.json, yarn.lock
Revert @oclif/pluign-update to 1.5.0
The latest version does not allow to update
N/A
https://github.com/eclipse/che/issues/21042
N/A
=> fix: revert @oclif/pluign-update to 1.5.0

src/commands/server/delete.ts, src/tasks/installers/olm-dev-workspace-operator.ts, src/tasks/installers/olm.ts
Only `chectl` must deploy upstream version of Dev Workspace operator from a custom catalog source.
N/A
https://issues.redhat.com/browse/CRW-2663
N/A
=> fix: Only chectl must deploy Dev Workspace operator

.ci/openshift-ci/Dockerfile
Update NodeJs to 16.x for e2e tests on OpenShift CI
N/A
https://github.com/eclipse/che/issues/21075
N/A
=> ci: Update NodeJs to 16.x for e2e tests on OpenShift CI

src/tasks/installers/olm-dev-workspace-operator.ts, src/tasks/installers/olm.ts
The channel name for next version of Dev Workspace operator has been changed to `next`
fix: deploy DevWorkspace from `next` channel instead of `fast`
N/A
N/A
N/A
=> fix: deploy DevWorkspace from `next` channel instead of `fast`

src/tasks/platforms/minikube.ts, yarn.lock
Update che-operator dependency
N/A
N/A
N/A
=> chore: Update che-operator dependency

package.json, yarn.lock
Remove workspace & auth commands topics
N/A
https://issues.redhat.com/browse/CRW-2699
N/A
=> fix: Remove workspace & auth commands topics

.github/workflows/release.yml
Fix release workflow not checking out the repo
=> fix: fix release script

src/commands/server/deploy.ts
Improve OIDC check
https://github.com/eclipse/che/issues/21049#issuecomment-1021135308
N/A
https://github.com/eclipse/che/issues/20909
N/A
=> fix: Improve OIDC check

.github/workflows/minikube-chectl-commands-tests.yml, README.md, src/api/version.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/common-flags.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/olm.ts, src/util.ts, test/e2e/e2e-upgrade.test.ts, test/e2e/e2e.test.ts, test/e2e/util.ts, yarn.lock
Drop `--version` flag
N/A
https://github.com/eclipse/che/issues/21001
N/A
=> chore: Drop --version flag

src/api/kube.ts, src/util.ts
chore: handle convension webhook error
N/A
N/A
N/A
=> chore: handle convension webhook error

src/api/kube.ts, src/api/version.ts, src/commands/server/deploy.ts, src/tasks/che.ts, src/tasks/component-installers/cert-manager.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/operator.ts, src/tasks/kube.ts, src/tasks/platforms/api.ts, src/tasks/platforms/common-platform-tasks.ts, src/tasks/platforms/crc.ts, src/tasks/platforms/docker-desktop.ts, src/tasks/platforms/k8s.ts, src/tasks/platforms/microk8s.ts, src/tasks/platforms/minikube.ts, src/tasks/platforms/openshift.ts, src/util.ts
Adapt chectl to CheCluster V2
N/A
N/A
N/A
=> chore: Adapt chectl to CheCluster V2

src/api/kube.ts, src/constants.ts, src/util.ts
Don't set tlsSecretName for OpenShift
N/A
N/A
N/A
=> fix: Don't set tlsSecretName for OpenShift

src/api/kube.ts, src/commands/server/update.ts, src/constants.ts, src/tasks/component-installers/cert-manager.ts, src/tasks/installers/operator.ts, src/util.ts
Adapt CheCluster V2 Operator update
N/A
N/A
N/A
=> fix: Adapt CheCluster V2 Operator update

prepare-che-operator-templates.js, src/api/context.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/tasks/installers/operator.ts, yarn.lock
Adapt ot CheCluster V2
N/A
https://github.com/eclipse/che/issues/20758
N/A
=> chore: Adapt ot CheCluster V2

src/tasks/installers/operator.ts
chore: Reorder operator tasks
N/A
N/A
N/A
=> chore: Reorder operator tasks

prepare-che-operator-templates.js, src/api/kube.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/deploy.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/tasks/che.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts
chore: Reorder delete tasks
N/A
N/A
N/A
=> chore: Reorder delete tasks

src/tasks/installers/operator.ts
fix: Rename webhook service
N/A
N/A
N/A
=> fix: Rename webhook service

src/api/kube.ts, src/tasks/installers/common-tasks.ts
Adopt chectl to CheCluster API v2
N/A
https://github.com/eclipse/che/issues/20758
N/A
=> feat: Adopt chectl to CheCluster API v2

src/commands/cacert/export.ts, src/commands/dashboard/open.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/status.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/util.ts, yarn.lock
https://github.com/eclipse/che/issues/21311
N/A
N/A
N/A
=> feat: Autodetect Eclipse Che namespace

src/api/kube.ts, src/tasks/installers/common-tasks.ts
Rename operands -> components
N/A
https://github.com/eclipse/che/issues/20758
N/A
=> fix: Rename operands -> components

README.md, src/commands/server/deploy.ts, src/constants.ts, test/e2e/e2e.test.ts, yarn.lock
Remove obsolete `olm-suggested-namespace` flag to allow to deploy operator in `openshift-operators` namespace
https://github.com/eclipse/che/issues/21424
`./run server:deploy -p openshift`
=> chore: Remove obsolete olm-suggested-namespace flag

README.md, package.json, src/commands/server/deploy.ts, src/constants.ts, test/e2e/e2e.test.ts, yarn.lock
chore: Remove obsolete olm-suggested-namespace flag (#2123); update to latest in che-operator 7.46.x sources
Change-Id: Ia514575667a939ffa8f210f7efc10c1d9fe447c2
Signed-off-by: Nick Boldt <nickboldt@gmail.com>
N/A
Cherry pick of https://github.com/che-incubator/chectl/pull/2123 to 7.46.x branch. Fixes https://github.com/eclipse/che/issues/21424 and https://issues.redhat.com/browse/CRW-2998
N/A
=> chore: Remove obsolete olm-suggested-namespace flag (#2123); update to latest in che-operator 7.46.x sources

src/api/kube.ts, src/tasks/installers/operator.ts, yarn.lock
chore: Find and delete OAuthClient object by label selector
N/A
https://github.com/eclipse/che/issues/20804
N/A
=> chore: Find and delete OAuthClient object by label selector

prepare-che-operator-templates.js, yarn.lock
Update CheCluster V2 templates
N/A
https://github.com/eclipse/che/issues/20758
N/A
=> feat: Update CheCluster V2 templates

src/tasks/installers/operator.ts, yarn.lock
fix: server delete command
N/A
N/A
N/A
=> fix: server delete command

src/commands/cacert/export.ts, src/commands/dashboard/open.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/status.ts, src/commands/server/stop.ts, src/commands/server/update.ts, yarn.lock
fix: Set default Eclipse Che namespace
N/A
https://issues.redhat.com/browse/CRW-3066
N/A
=> fix: Set default Eclipse Che namespace

src/api/kube.ts, src/util.ts
Handle WebHook availability error when CheCluster CR is created
N/A
N/A
N/A
=> fix: Handle WebHook availability error when CheCluster CR is created

src/api/kube.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, src/tasks/platforms/crc.ts, src/tasks/platforms/docker-desktop.ts, yarn.lock
Respect `--chenamespace` flag
N/A
https://issues.redhat.com/browse/CRW-3082
Deploy Eclipse Che in any namespace but eclipse-che
=> fix: Respect --chenamespace flag

src/tasks/installers/olm.ts
Use CheCluster API v2 sample
N/A
https://issues.redhat.com/browse/CRW-3082
N/A
=> fix: Use CheCluster API v2 sample

yarn.lock
chore: Update operator dependency
N/A
N/A
N/A
=> chore: Update operator dependency

src/api/che.ts, src/api/context.ts, src/api/kube.ts, src/commands/server/delete.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/constants.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts, src/tasks/installers/olm-dev-workspace-operator.ts, src/tasks/installers/olm.ts, yarn.lock
Rework olm installer:
* fixed but using custom catalog source
* CatalogSource goes into `openshift-marketplace` namespace only
* Subscription goes into `openshift-operaetors` namspace only
* minor improvements
N/A
https://github.com/eclipse/che/issues/21542
N/A
=> feat: Rework olm installer

src/tasks/installers/olm.ts
Fix ceck CheCluster existence typo
N/A
https://issues.redhat.com/browse/CRW-3218
N/A
=> fix: Fix check CheCluster existence typo

README.md, src/api/context.ts, src/api/kube.ts, src/api/version.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, src/tasks/platforms/api.ts, src/util.ts, yarn.lock
Allow only OLM installer for OpenShift platform
```
./run server:deploy --platform openshift --installer operator                                                                                                                             2 ↵ ──(Mon,Aug08)─┘
(node:380620) Warning: Mismatched version in chectl plugin manifest. Expected: 0.0.2 Received: main
This usually means you have an oclif.manifest.json file that should be deleted in development. This file should be automatically generated when publishing.
(Use `node --trace-warnings ...` to show where the warning was created)
› Current Kubernetes context: 'default/api-ci-ln-5tpxxht-72292-origin-ci-int-gce-dev-rhcloud-com:6443/kube:admin'
✔ Verify Kubernetes API...[OK] [OpenShift]
✔ 👀 …
```
=> chore: Allow only OLM installer for OpenShift platform

make-release.sh, prepare-templates.js, yarn.lock
chore: Update dependency
N/A
https://github.com/eclipse/che/issues/21710
N/A
=> chore: Update dependency

.github/workflows/release.yml, make-release.sh
=> fix: make-release.sh

.github/workflows/release.yml, make-release.sh
=> fix: release action

make-release.sh
=> fix: release script fix

prepare-templates.js, src/api/kube.ts, src/tasks/installers/operator.ts
chore: Support org.eclipse.che MutatingWebhookConfiguration
N/A
https://github.com/eclipse/che/issues/21768
N/A
=> chore: Support org.eclipse.che MutatingWebhookConfiguration

README.md, src/tasks/installers/operator.ts
fix: syntax error in operator.ts
=> fix: syntax error in operator.ts

prepare-templates.js, src/api/kube.ts, src/commands/server/delete.ts, src/commands/server/stop.ts, src/constants.ts, src/tasks/installers/operator.ts, yarn.lock
* Refactor delete tasks
* Delete SCC and related resources
N/A
https://github.com/eclipse/che/issues/21768
N/A
=> chore: Delete SCC and related resources

.github/workflows/pr-check.yml, README.md
chore: #21790 add badges for some actions and a link to downstream 3.x job; clean up name shown in badge
Change-Id: I5cd0b9b200301e5b7f3d5324aef3432b8119e4a3
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: #21790 add badges for some actions and a link to downstream 3.x job

.github/workflows/release-build-and-push-to-GH-releases.yml
feat: Add chectl binaries for darwin-arm64 arch
N/A
https://github.com/eclipse/che/issues/21783
N/A
=> feat: Add chectl binaries for darwin-arm64 arch

README.md, src/api/kube.ts, src/tasks/installers/operator.ts
fix: Allow to deploy Eclipse Che in non default namespace
N/A
N/A
`./run server:deploy -p minikube -n test`
=> fix: Allow to deploy Eclipse Che in non default namespace

src/commands/server/delete.ts
fix: Don't allow to delete openshift-operators namespace
N/A
https://github.com/eclipse/che/issues/21802
N/A
=> fix: Don't allow to delete openshift-operators namespace

make-release.sh
Change-Id:...
chore: rebase when pulling
Change-Id: I3d9ed859c2bbe0ea9fa1cdd055907ccc9150a5cb
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: rebase when pulling

src/context.ts, src/hooks/prerun/new-version-warning.ts, src/tasks/installers/dev-workspace/devworkspace-olm-installer.ts, src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts, src/utils/utls.ts
fix: Make downstream project (dsc) compilable
N/A
https://issues.redhat.com/browse/CRW-3353
N/A
=> fix: Make downstream project (dsc) compilable

src/tasks/platforms/crc.ts, src/tasks/platforms/platform-tasks.ts
chore: Rename CodeReady Containers into OpenShift Local
N/A
https://github.com/eclipse/che/issues/21849
N/A
=> chore: Rename CodeReady Containers into OpenShift Local

src/api/kube-client.ts, src/tasks/che-tasks.ts, src/tasks/installers/dev-workspace/dev-workspace-tasks.ts, src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts, src/tasks/installers/eclipse-che/eclipse-che-tasks.ts, src/tasks/platforms/minikube.ts, src/tasks/pod-tasks.ts
fix: CR deletion
N/A
https://issues.redhat.com/browse/CRW-3353
N/A
=> fix: CR deletion

yarn.lock
chore: Update operator dependencies
=> chore: Update operator dependencies

.github/workflows/codecov.yml, .github/workflows/minikube-chectl-commands-tests.yml, .github/workflows/minikube-chectl-release-test.yml, .github/workflows/pr-check.yml, .github/workflows/release-announce.yml, .github/workflows/release-build-and-push-to-GH-releases.yml, .github/workflows/release.yml, .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Updates Ubuntu to 22.04 and to use the node 16 versions of actions wherever possible
https://github.com/eclipse/che/issues/21763
=> Chore: update ubuntu to 22.04 and actions to use node 16 for #21763

src/commands/server/deploy.ts, src/context.ts, src/tasks/installers/eclipse-che/eclipse-che-tasks.ts
* support `next` channel, equal to `fast` 
* support `latest` channel
N/A
https://issues.redhat.com/browse/CRW-3877
N/A
=> feat: Support deploy DS from latest and next channels

README.md, src/flags.ts, src/tasks/installers/dev-workspace/devworkspace-olm-installer.ts, src/tasks/olm-tasks.ts
fix: --skip-devworkspace-operator flag usage
N/A
https://github.com/eclipse/che/issues/21980
N/A
=> fix: --skip-devworkspace-operator flag usage

install.sh
fix: Preserve PATH environment variable
N/A
https://github.com/eclipse/che/issues/22070
N/A
=> fix: Preserve PATH environment variable

src/api/kube-client.ts, src/utils/che.ts
fix: Ensure plugin-registry configmap exists before reading
N/A
https://issues.redhat.com/browse/CRW-4171
N/A
=> fix: Ensure plugin-registry configmap exists before reading

.ci/oc-test-happy-path.sh
Fixed outdated npm script name 
n/a
https://github.com/eclipse/che/issues/22153
/test
=> fix: updated HAPPY_PATH_SUITE in oc-test-happy-path.sh

.github/workflows/release-announce.yml, .github/workflows/release-build-and-push-to-GH-releases.yml
remove deprecated set-output command
https://github.com/eclipse/che/issues/21993
=> chore: che-21993 replace deprecated set-output in actions

README.md, yarn.lock
Add Trademark notice
https://github.com/eclipse/che/issues/21944
=> chore: che-21944 Add Trademark notice to README.md

src/api/kube-client.ts
fix: Prevent handging while waiting kubernetes resources
N/A
https://issues.redhat.com/browse/CRW-3897
N/A
=> fix: Prevent handging while waiting kubernetes resources

resources/dex/ingress.yaml
feat: specify IngressClassName for `dex` ingress
N/A
https://github.com/eclipse/che/issues/22175
N/A
=> feat: specify IngressClassName for `dex` ingress

src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts
Don't create ICSP if DS is being deployed from the stable channel
N/A
https://issues.redhat.com/browse/CRW-4503
N/A
=> fix: Don't create ICSP if DS is being deployed from the `stable` channel

.vscode/launch.json, .vscode/tasks.json, bin/debug, devfile.yaml
* reworked tasks.json
N/A
https://github.com/eclipse/che/issues/22243
N/A
=> feat: [chectl] devfile improvements

src/hooks/analytics/segment-adapter.ts, yarn.lock
Get country and return it as a string instead of array
Issue: https://github.com/che-incubator/chectl/issues/2720
=> fix: Return country as a string instead of array

src/commands/server/update.ts, src/context.ts, src/tasks/installers/dev-workspace/devworkspace-olm-installer.ts, src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts, yarn.lock
Allows to use `--skip-devworkspace-operator` flag for `server:update` command by skipping updating DWO.
N/A
https://issues.redhat.com/browse/CRW-4575
=> chore: Adapt --skip-devworkspace-operator flag for server:update command

src/context.ts, src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts
chore: wait for operator pod ready once sub is created
N/A
https://issues.redhat.com/browse/CRW-4794
N/A
=> chore: wait for operator pod ready once sub is created

.ci/openshift-ci/Dockerfile
chore: Update Node version in Dockerfile for OpenShift tests
https://issues.redhat.com//browse/CRW-4820
=> chore: Update Node version in Dockerfile for OpenShift tests

.ci/oc-test-happy-path.sh, .ci/openshift-ci/Dockerfile
fix: HappyPath tests
see https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/che-incubator_chectl/2737/pull-ci-che-incubator-chectl-7.74.x-v12-chectl-devworkspace-happy-path/1699805771564322816
=> fix: HappyPath tests

.ci/openshift-ci/Dockerfile
Installing `jq` into the container
=> fix: Running HappyPath tests on OpenShift CI

.github/workflows/release-announce.yml, .github/workflows/release-build-and-push-to-GH-releases.yml, .github/workflows/release.yml
chore: Remove mattermost notifications
=> chore: Remove mattermost notifications

src/tasks/installers/eclipse-che/eclipse-che.ts
Use correct operator selector `app=che-operator`
N/A
https://issues.redhat.com/browse/CRW-4848
N/A
=> fix: Use correct operator selector app=che-operator

.github/workflows/release-build-and-push-to-GH-releases.yml, README.md, package.json, yarn.lock
fix: setting chectl version on release
N/A
https://issues.redhat.com/browse/CRW-4922
N/A
=> fix: setting chectl version on release

package.json, src/commands/dashboard/open.ts, yarn.lock
fix: dashboard:open command
N/A
https://issues.redhat.com/browse/CRW-4922
N/A
=> fix: dashboard:open command

.github/workflows/release.yml
Change-Id:...
install hub and other deps
Change-Id: I6f50c832bc0f1d49ab69494d76c851a2ca9a4274
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: install hub and other deps [ci skip]

README.md, package.json, yarn.lock
fix: Revert plugin update
N/A
Fix issue with updating chectl to the next version
N/A
=> fix: Revert plugin update

yarn.lock
=> fix: Update dependencies

prepare-templates.js, yarn.lock
chore: operator roles sanitizing
N/A
https://github.com/eclipse/che/issues/22811
N/A
=> chore: operator roles sanitizing

src/tasks/che-tasks.ts
chore: Increase Che active waiting timeout
N/A
https://github.com/eclipse/che/issues/22895
N/A
=> chore: Increase Che active waiting timeout

.github/workflows/minikube-chectl-commands-tests.yml, README.md
Download chectl install script from che-incubator.github.io
https://github.com/eclipse-che/che/issues/22925
=> Fix URL where to download chectl install script from

src/tasks/che-cluster-tasks.ts
fix: Apply CheCluster patch
N/A
https://github.com/eclipse-che/che/issues/22978
N/A
=> fix: Apply CheCluster patch

src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts
chore: Delete the order of removing resources
N/A
https://issues.redhat.com/browse/CRW-6625
N/A
=> chore: Change the order of removing resources

src/tasks/installers/eclipse-che/eclipse-che-olm-installer.ts
chore: Change the order of removing resources
N/A
https://issues.redhat.com/browse/CRW-6625
N/A
=> chore: Change the order of removing resources (#2892)

src/tasks/common-tasks.ts
chore: clean up
N/A
https://github.com/eclipse-che/che/issues/23026
N/A
=> chore: clean up

src/context.ts
Don't throw error if openshift version is absent in the response
N/A
https://github.com/eclipse-che/che/issues/23037
N/A
=> fix: Improve openshift version detection

channels/next/linux-arm, channels/next/linux-ppc64le, channels/next/linux-s390x, channels/next/win32-x86, channels/stable/linux-arm, channels/stable/linux-ppc64le, channels/stable/linux-s390x, channels/stable/win32-x86, download-link/next-linux-arm, download-link/next-linux-ppc64le, download-link/next-linux-s390x, download-link/next-win32-x86, download-link/stable-linux-arm, download-link/stable-linux-ppc64le, download-link/stable-linux-s390x, download-link/stable-win32-x86, install.sh
Fix installation script for different platforms including arm64
N/A
https://github.com/eclipse-che/che-operator/pull/1959
N/A
=> fix: Installation script for different platforms including arm64

channels/next/linux-arm64, channels/stable/linux-arm64, download-link/next-linux-arm64, download-link/stable-linux-arm64
Add linux-arm64 download links
N/A
N/A
N/A
=> chore: add linux-arm64 download links

README.md, devfile.yaml
=> chore: bump devfile schemaVersion + add badges to README.md

install.sh
chore: Support arm64 platform
N/A
https://github.com/eclipse-che/che/issues/23405
=> chore: Support arm64 platform

package.json, src/api/che-logs-reader.ts, src/api/kube-client.ts, yarn.lock
chore: Update k8s client to 0.22.3
N/A
https://github.com/eclipse-che/che/issues/23396
=> chore: Update k8s client

src/context.ts
fix: Path to templates dir
N/A
https://issues.redhat.com/browse/CRW-9218
N/A
=> fix: Path to templates dir

.github/workflows/generate-sbom.yml, README.md
This PR aims to bootstrap the EF Security Team initiative of supporting projects in implementing automated SBOM generation and upload workflows, with the goal of enhancing software supply chain security.
We wanted this to seamlessly integrate with your existing release processes, so we implemented 1 workflow meant to generate an SBOM for the `chectl` product.
Currently the workflow is triggered by new releases being published. A polyglot SBOM generation tool (`cdxgen`) is used to generate the SBOM, which is then uploaded as an artifact. The `store-sbom-data` reusable workflow stores additional metadata about the project and upon completion, the self service system downloads the SBOM from artifacts and uploads it to our DependencyTrack [instance](https://sbom.eclipse.org/), under the …
=> chore: add sbom generation and upload workflow
