src/helpers/che.ts, test/helpers/che.test.ts
server:start failed if che namespace existed but the ingress did not
=> Fix ingress problem with server:start

README.md, package.json, yarn.lock
closes #29
The PR adds `autocomplete` command with the [`@oclif/plugin-autocomplete`](https://github.com/oclif/plugin-autocomplete).
`chectl autocomplete` command displays the instructions to install an autocomplete script for `chectl`.
=> Add command for installing an autocomplete script

README.md, src/commands/workspace/inject.ts, src/helpers/che.ts, test/helpers/che.test.ts
closes #31 
The PR introduces `chectl workspace:inject` command for pushing the local Kubernetes configuration into a Che Workspace.
=> Add 'inject' command

README.md, src/commands/workspace/start.ts, src/helpers/che.ts, test/helpers/che.test.ts, test/helpers/replies/create-workspace-from-valid-workspaceconfig.json, test/helpers/requests/workspaceconfig.valid
```
$ chectl workspace:start --help
(...)
-w, --workspaceconfig=workspaceconfig  path to a valid workspace configuration json file
```
=> Support creating workspaces with a workspace config JSON

.travis.yml, README.md, src/commands/server/start.ts
Fix README being changed every time
so if in current directory, there is a templates folder, use it
fallback to embedded location
Change-Id: I841f3f88b39e712f0c17a217624fa255369d80e4
=> Make templates being resolved either locally or from embedded location

README.md, package.json, src/commands/server/start.ts, src/installers/minishift-addon.ts, test/installers/minishift-addon.test.ts
Added a new installer: [minishift-addon](https://github.com/minishift/minishift/tree/master/addons/che). 
This installer is the default minishift installer for Che single-user (for multi-user it's still the operator). 
Minikube defaults are helm for Che single-user, the operator for multi-user.
=> Added minishift-addon: minishift default single-user installer

package.json, src/platforms/minikube.ts, src/platforms/minishift.ts
Ensure userland-proxy has been defined on minikube or minishift before deploying che.
Change-Id: Iea000a65c26cca00972deea498d6131eb3c5709b
=> Only start che on minishift and minikube if userland-proxy is disabled

.travis.yml
allow to know which version we have
https://github.com/che-incubator/chectl/issues/69
Change-Id: I03f9b5fb7ee46fe100c8ddd9bb674af2dec127ad
=> Include the short sha1 in the version of chectl

README.md, src/api/che.ts, src/api/kube.ts, src/api/openshift.ts, src/commands/server/delete.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts, src/installers/helm.ts, src/installers/minishift-addon.ts, src/installers/operator.ts, src/platforms/minikube.ts, src/platforms/minishift.ts, test/api/che.test.ts, test/api/kube.test.ts, test/api/openshift.test.ts, test/api/replies/get-keycloak-settings.json, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts
With this PR the command `server:stop`:
-  calls Che server shutdown endpoint (`/api/system/stop?shutdown=true`) 
- scales down the deployment to zero (as well as keycloak and postgres if needed)
In this PR is also included a new command: `server:delete`. It rapidly purges all Che resources (deployments, pods, services, routes, cm, pvc etc...) to start from scratch.
Some other changes included in this PR:
- Automatically find out if it's Kubernetes or OpenShift (currently only stop and delete commands)
- server:stop is the first command that supports authenticated Che API (user has to provide the access token as a param, I would like to create a new auth:token command that would help with that)
- Added 2 end2end tests for minikube and minishift: I would like to setup a circleCi job that …
=> Chang server:stop behavior and added server:delete

README.md, src/api/che.ts, src/commands/workspace/inject.ts
closes #59 
Executing `chectl workspace:inject` command without a container specified (`-c` option) injects a configuration file in all containers of a Workspace pod.
Tasks are running in parallel indicating the status of each.
See the example of output when injecting kubeconfig in the Workspace with 4 containers.
=> Inject configuration files in all containers if it's not specified

devfile.yaml
Che 7.0.0-beta-4.0 is going to drop support for component names and replaces it with an alias. We need to update the devfile.yaml to take that into account.
=> Use alias in devfile.yaml and remove component names.

devfile.yaml, templates/che-operator/config.yaml, test/api/replies/create-workspace-from-valid-devfile.json, test/api/replies/create-workspace-from-valid-workspaceconfig.json, test/api/requests/devfile.invalid, test/api/requests/devfile.valid, test/api/requests/workspaceconfig.valid, test/api/requests/workspaceconfig.valid2
Do not merge before https://github.com/eclipse/che/pull/13204 gets merged
=> Adapt chectl to new plugin notation

templates/kubernetes/helm/che/templates/cert-issuer.yaml, templates/kubernetes/helm/che/templates/certificate.yaml, templates/kubernetes/helm/che/values.yaml
Fix few typos for making `global.tls.enabled` work.
=> Fix TLS templates typos

src/commands/server/start.ts
Fixes #48 and #103
If pod is already in running state, do not wait for scheduling
Change-Id: Ibd3f8ced681140691fdcc3cc6e7b9068d7d2ec6b
=> Check running state before waiting for a pod

templates/kubernetes/helm/che/templates/configmap.yaml, templates/kubernetes/helm/che/templates/deployment.yaml, templates/kubernetes/helm/che/templates/workspace-exec-role-binding.yaml, templates/kubernetes/helm/che/templates/workspace-view-role-binding.yaml
Fixes #108
With helm 2.14.0 the templates are validated, thus it should contain valid entries
also RoleRef doesn't contain namespace https://godoc.org/k8s.io/api/rbac/v1beta1#RoleRef
and securityContext.fsGroup is part of pod def, not container def https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
Change-Id: I24ee1935d931efcbf13440303ca544b653cfa91c
=> Helm: use valid templates

src/commands/workspace/start.ts
Fixes #28
```
$ ./bin/run workspace:start 
›   Error: workspace:start command is expecting a devfile or workspace configuration parameter.
```
=> Ensure there is a flag when using workspace:start command

README.md, src/api/che.ts, src/commands/devfile/generate.ts, src/commands/workspace/start.ts, test/api/che.test.ts
Support `chectl workspace:start --devfile=http://...` and fix `devfile:generate` yaml dump
=> Support starting workspaces from remote devfiles

README.md, package.json, yarn.lock
It fixes #72
note:it's working if you're using one of the binary provided by `oclif-dev:pack` command and not the 'single binary' currently provided in release section
Change-Id: I23365a01dd2160d100470aeea966bebd2e116907
=> Provide update command that is allowing self-update of the binary

README.md, src/api/che.ts, src/commands/workspace/start.ts, test/api/che.test.ts
Each time a developer creates a workpace from the same devfile, if the workspace name already exist, che would suffix it with an underscore char + incremental number.
This PR provides the ability to customize this name in the case user would like to name its workspace differently. For instance name could containsindication about the task/issue or anything else.
Previously, without the option:
```
chectl workspace:start --devfile=devfile.yaml
✔ Retrieving Che Server URL...http://che-che.192.168.39.216.nip.io
✔ Verify if Che server is running
✔ Create workspace from Devfile devfile.yaml
Workspace IDE URL:
http://che-che.192.168.39.216.nip.io/dashboard/#/ide/che/chectl_3
```
Now with the option `--name=`
```
chectl workspace:start --devfile=devfile.yaml --name=chectl-fix-component-name
✔ …
```
=> option to override workspace name when creating a workspace from a devfile

src/commands/devfile/generate.ts
Thanks to daniel that worked on that PR during https://hack-commit-pu.sh/ :)
When using chectl devfile:generate with the dockerimage option and when it docker image contains a character like `:`, the workspace is failing to start because alias name container `:` which is not allowed in Che.
How to reproduce:
Run the command and start the workspace from the generated file:
```
$ chectl devfile:generate --dockerimage=maven:3.6.0-jdk-11 > test.devfile.yaml
$ chectl workspace:start -f test.devfile.yaml
✔ Retrieving Che Server URL...http://che-che.192.168.39.25.nip.io
✔ Verify if Che server is running
✔ Create workspace from Devfile test.devfile.yaml
Workspace IDE URL:
http://che-che.192.168.39.25.nip.io/dashboard/#/ide/che/chectl-generated
```
=> chectl devfile:generate. Fixed dockerimage alias that contains invalid characters

README.md
A short inclusion in the readme to explain how to install chectl binary on macOS using the command-line tool cURL.
=> Update README.rm : chectl installation on macOS

README.md, src/api/kube.ts, src/commands/server/start.ts, src/installers/operator.ts, src/platforms/docker-desktop.ts, src/platforms/k8s.ts, src/platforms/openshift.ts, test/platforms/openshift.test.ts
`--platform=openshift` , `--platform=k8s` or `--platform=docker-desktop`
It fixes https://github.com/che-incubator/chectl/issues/14 and fixes https://github.com/che-incubator/chectl/issues/80
note: you need to be logged in on the underlying platform before running chectl
I've tested by using Openshift v3.11 on RHPDS and on K8S/digitalocean and Docker Desktop for mac
example with command
```$ chectl server:start --platform=docker-desktop```
note: using operator is still failing on workspaces due to https://github.com/che-incubator/chectl/issues/92
Change-Id: Ic541c5d7932c6782c67bc0103a0d941fd34288d6
=> Add initial support for openshift, k8s and docker-desktop platforms

src/installers/operator.ts
fix #161 
trying with RC2 resulted in having RC2 image for che-server
```
Type    Reason     Age   From               Message
----    ------     ----  ----               -------
Normal  Scheduled  47s   default-scheduler  Successfully assigned che/che-7c9677d4d6-fmjdj to minikube
Normal  Pulling    46s   kubelet, minikube  Pulling image "eclipse/che-server:7.0.0-RC-2.0"
Normal  Pulled     29s   kubelet, minikube  Successfully pulled image "eclipse/che-server:7.0.0-RC-2.0"
```
Change-Id: I522ebfa7e37f8063a4f0a8824cef6ad77b7dfdf0
=> allow to override CHE_IMAGE parameter with the custom flags --cheImage for che operator

README.md, src/installers/helm.ts, yarn.lock
Fix #18
`$ helm history` will display now
```shell
29      	Wed Jul  3 11:00:29 2019	SUPERSEDED	che-0.1.0	Rollback to 28   
30      	Wed Jul  3 11:00:30 2019	DEPLOYED  	che-0.1.0	Upgrade complete 
```
Change-Id: I30a7e4462d5c10219c216ee528e73f2853aeaba5
=> Handle deleted state of che helm chart by rollbacking or purging the charts

src/api/kube.ts, test/api/kube.test.ts, test/api/replies/get-secrets.json, test/api/replies/get-serviceaccounts.json
It fixes https://github.com/eclipse/che/issues/13800
Grab secret from serviceAccount and use it when calling the endpoint
I've tested on a remote k8s and docker-desktop
Change-Id: I5daf5df41d8cebc51ef501c629eca65bc63ae729
=> fix(k8s): token missing in endpoint when calling /healthz

src/api/che.ts, src/commands/workspace/start.ts
Adds a flag to provide the token
It fixes https://github.com/eclipse/che/issues/13828
```
$ chectl workspace:start --access-token=${JWT_TOKEN} -f <(./bin/run devfile:generate --name=minimal-wksp)
✔ Retrieving Che Server URL...http://che-che.192.168.99.127.nip.io
✔ Verify if Che server is running...RUNNING (auth enabled)
✔ Create workspace from Devfile /dev/fd/63
Workspace IDE URL:
http://che-che.192.168.99.127.nip.io/dashboard/#/ide/florent/minimal-wksp
```
Change-Id: I05e27dab4409624e29648a9660106e4711676064
=> fix(workspace): fix workspace:start command with authentication enabled

package.json, yarn.lock
Self-update `eclipse/che` and `eclipse/che-operator` dependencies when running yarn install command.
So yarn.lock is using latest master versions every time it's used.
Change-Id: I430aa868b07cbc954de699154ad070b3cca42756
=> fix(yarn.lock): Old templates were used as yarn.lock is locking sha-1 master

src/api/kube.ts, src/installers/helm.ts
For now tls let's encrypt certificates are failing as the default email is with example.com
But as we require che-tls secret with email inside, re-use this one (if `--tls` option is given)
And when cert-manager is not installed and that `--tls` option is enabled there are helm errors hard to understand for newcomers, so detect it automatically if cert-manager has been installed or not and provides guidance.
It completes fixes of https://github.com/eclipse/che/issues/13801
=> fix(helm): Automatically grab tls email from che-tls and checks for cert-manager

src/commands/server/start.ts, src/commands/server/stop.ts, src/installers/helm.ts
Registries will be deployed locally by default (https://github.com/eclipse/che/issues/13557), so we don't want to have default registries URL sent to helm.
This will now work just with helm chart. It must be synced with work on operator side.
=> remove devfile and plugin registries defaults

src/api/kube.ts, src/commands/server/start.ts, src/installers/operator.ts
This PR adds compatibility  with the last Che operator changes done in PR https://github.com/eclipse/che-operator/pull/51
This adds support for deploying registries along with the Che server from the operator.
=> fix(operator): Add compatibility with the last operator changes

src/api/kube.ts
Don't deploy a registry if its url is specified as an argument when installing with the operator.
This PR is to have, with the `operator` installer, the same behavior as the `helm` installer: https://github.com/che-incubator/chectl/blob/master/src/installers/helm.ts#L210
This is related to https://github.com/eclipse/che/issues/13557
=> fix(operator): Don't deploy a registry if its url is specified as an argument

.travis.yml, package.json
Assemblies were missing the lib folder. It's because with the newer typescript if the outDir is removed we also need to remove tsconfig.tsbuildinfo else the incremental build thinks that everything is up-to-date and then it doesn't generate the files again
Also remove from tgz the chectl-* files that are the pkg executable files
It fixes https://github.com/eclipse/che/issues/13872
Change-Id: Id7a79c37bde9018b3a1f49d50e5d600cdf758a9e
=> chore(travis): Fix assemblies build (.tgz)

README.md, src/commands/server/start.ts, src/installers/helm.ts
**TODO** revise `--chenamespace=chenamespace` parameter
1. Fixes documentation since `--tls` does not enable multiuser anymore.
2. The only server strategy that works is `multi-host` and it requires wildcards certificates. It's why helm chart does not include cluster issuer and certificates anymore. User must provide `che-tls` secret with certificate content.
It's why checking that cert-manager is set is removed, as well as propagating `tls.email` parameter.
It's tested on GCP with the following configurations:
```
./bin/run server:start -a=helm -p=k8s -b=che.gcps.my-ide.cloud --tls --multiuser
```
```
./bin/run server:start -a=helm -p=k8s -b=che.gcps.my-ide.cloud --tls
```
```
./bin/run server:start -a=helm -p=k8s -b=che.gcps.my-ide.cloud --multiuser
```
It's needed after …
=> Adapt chectl to fixes for TLS for helm chart

src/platforms/microk8s.ts, src/platforms/minikube.ts, src/platforms/minishift.ts
Do not ignore the domain parameter if it's specified.
https://github.com/eclipse/che/issues/14095
=> fix(platform): server:start with specified domain

README.md, src/api/kube.ts, src/commands/server/start.ts, src/installers/helm.ts
Fixes deploying Che with helm installer when self-signed-cert is specified
It's related to https://github.com/eclipse/che/issues/14035
It depends on https://github.com/eclipse/che/pull/14176
=> fix(helm): fix deploying che with helm installer when self-signed-cert is specified

src/api/che.ts, src/api/kube.ts, src/commands/devfile/generate.ts, src/commands/server/delete.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts, src/installers/helm.ts, src/installers/minishift-addon.ts, src/installers/operator.ts, src/platforms/microk8s.ts, src/platforms/minikube.ts, src/platforms/minishift.ts, src/platforms/openshift.ts, test/api/che.test.ts, test/commands/devfile/generate.test.ts, test/commands/server/start.test.ts, test/commands/server/stop.test.ts, test/installers/minishift-addon.test.ts, test/platforms/microk8s.test.ts, test/platforms/minikube.test.ts, test/platforms/minishift.test.ts, test/platforms/openshift.test.ts, types/listr.d.ts
It contains some minor fixes that are separate by self-describing commits.
Here I'm adding some context to some of them:
1. fix: fix formatting in ts files
It's a pretty weird thing when you modify a few lines in a file, use `Format document` feature and some extra lines are modified as well with formatting fixes only.
I performing formatting of code, and hopefully, if everyone won't merge unformatted code, then we won't get such situation anymore.
I tried to automate a process of formatting but failed because of the following issues 
https://github.com/microsoft/TypeScript/issues/11629
https://github.com/vvakame/typescript-formatter/issues/118
2. fix: Fixes checking if Che Server is available
`isCheServerReady` method requires che URL and at the same time checks if namespace already …
=> Various small fixes

README.md, src/api/kube.ts, src/commands/server/start.ts
fix(operator): fix deploying on K8s with operator and TLS 
https://github.com/eclipse/che/issues/14102
=> fix(operator): fix deploying on K8s with operator and TLS 

.travis.yml
Make gh-pages being refreshed automatically after each release
https://github.com/eclipse/che/issues/14322
Change-Id: Ie017f64d5a13a54bec0e8bdc736605afc2c1a556
=> chore(travis): add gh-pages provider to make sure github pages are up-to-date

yarn.lock
Fix vulnerability reported by https://github.com/che-incubator/chectl/network/alert/yarn.lock/set-value/open
N/A
Change-Id: I87c024db7c7eca2f0bb1e5437ed255775d84dfa6
=> chore(deps): Fix vulnerability on set-value by bumping the value of yarn dependencies

src/installers/operator.ts
This PR fixes creating cluster role since now it's needed without os-oauth
It's needed to be able to create console links on OpenShift 4.2
https://github.com/eclipse/che-operator/pull/71
=> fix(operator): fix creating cluster role since now it's needed without os-oauth

src/commands/server/start.ts
Do not navigate too far in upper directories
Fix https://github.com/eclipse/che/issues/14484
Change-Id: Ic66a482eb2e697452b2f495404ea31ef016e4daa
=> fix(templates): parent directories of chectl may not be named chectl

src/api/che.ts, src/tasks/che.ts
Fixes pod selector for minishift addon installer
It became needed after merging https://github.com/minishift/minishift/pull/3333/files#diff-e2fbb6157fa0ac05d672c51b89aa421aR46 since minishift addon provides plugin and devfile registries with the same `app=che` label
=> fix(minishift-addon): fix pod selector for minishift addon installer

src/tasks/installers/operator.ts
Adds crc platform flag check as an option to
namespace creation.
Fixes https://github.com/eclipse/che/issues/14516
=> Fix missing crc flag check

src/tasks/platforms/docker-desktop.ts
Docker desktop has changed its kubernetes context
Fixes https://github.com/eclipse/che/issues/14718
Change-Id: I2d069050d692ac9b3398d88cc4e89c5ba5b3b28e
=> fix(docker-desktop): Handle another docker desktop context

src/api/kube.ts
Fix wrapping of k8s API messages.
The example response:
```json
{
"response": {
"statusCode": 422,
"body": {
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "customresourcedefinitions.apiextensions.k8s.io 'checlusters.org.eclipse.che' is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update",
"reason": "Invalid",
"details": {
"name": "checlusters.org.eclipse.che",
"group": "apiextensions.k8s.io",
"kind": "customresourcedefinitions",
"causes": [
{
"reason": "FieldValueInvalid",
"message": "Invalid value: 0x0: must be specified for an update",
"field": "metadata.resourceVersion"
}
]
},
"code": 422
},
"headers": {
"cache-control": "no-store",
"content-type": "application/json",
"date": "Thu, 10 Oct 2019 14:53:54 GMT", …
```
=> Fix wrapping of k8s api messages

.travis.yml, README.md, make-release.sh, src/api/kube.ts, src/commands/server/update.ts, src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/installers/operator.ts
Adds an ability to update Che deployed with an operator by executing a command `server:update`.
It's not a final state where we want `server:update` be but it's a good start point where we can start using it.
https://github.com/eclipse/che/issues/14793
1. Download chectl released version like [7.0.0](https://github.com/che-incubator/chectl/releases/tag/20190814170217), unpack it, remove `~/.local/share/chectl/client`, and make sure that chectl version returns correct version. And only then install Che with this chectl.
2. Remove `~/.local/share/chectl/client` and use chectl from this branch (.tar.gz for your OS can be found in the following [archive](https://dropmefiles.com/osUs7) for chectl:nightly for my branch) and do `/bin/run server:update --installer=operator --platform=minishift` …
=> Added an ability to update deployed Che with operator installer

src/api/kube.ts, src/tasks/installers/operator.ts
#384 # What does this PR do?
This PR fixes a number of issues in the chectl code that still prevent it to be used for installing the CRW flavor:
- Replace hard-coded value of the `che-operator` name by the corresponding variables, in order to allow using alternate values in the CRW case
- Allow deleting / creating again a deployment when it cannot be directly updated due to immutable fields
This references the following JIRA issue comment: https://issues.jboss.org/browse/CRW-462?focusedCommentId=13811780&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13811780
=> fix: Fix server update for CRW

src/api/kube.ts
Signed-off-by: David Festal <dfestal@redhat.com>
This PR fixes a bug that was introduced in the previous PR #394 
It should use the `await` instruction before returning from the function, in order to return **only after** the deployment has been created.
=> fix: Fixup previous PR #394 (missing `await` instruction)

src/api/kube.ts
CRW-483: The 'server:start' command of the 'oc' client fails on the OCP 3.11' cluster with state 'Running' / 'Pending' expected
https://issues.jboss.org/browse/CRW-483
=> CRW-483: The 'server:start' command of the 'oc' client fails on the OCP 3.11' cluster with state 'Running' / 'Pending' expected

src/tasks/platforms/microk8s.ts
`microk8s.status` can sometimes take longer than 1 second to execute, causing chectl to erroneously determine that it is not running.
This PR increases the timeout on the async call to microk8s.status from 1s to 10s.
I did not create an issue, as the change is very small and simple. This PR does, however, fix an issue I had on my machine with microk8s.status taking more than 1s to run.
=> fix: Increase microk8s.status timeout from 1s to 10s

_layouts/stable-channel.html, _layouts/stable-download-link.html
Use semVer order on chectl stable links
ordering by date is not good as for example `7.3.2` may be released after `7.4.0`
Fixes https://github.com/eclipse/che/issues/15321
Change-Id: I0587de4c2c0c2499399d37230ff0197cdfd449f5
=> fix(stable): Use semver for 'stable' versions

package.json, src/tasks/installers/helm.ts, test/tasks/installers/helm.test.ts, test/tasks/installers/minishift-addon.test.ts, test/tasks/platforms/crc.test.ts
feat(helm): Add support for helm v3
Fixes https://github.com/eclipse/che/issues/15235
I tested with docker-desktop
```
$ chectl server:start --platform=docker-desktop --installer=helm
✔ Verify Kubernetes API...OK
✔ 👀  Looking for an already existing Che instance
✔ Verify if Che is deployed into namespace "che"...it is not
✔ ✈️  Docker Desktop preflight checklist
✔ Verify if kubectl is installed
✔ Verify if kubectl context is Docker Desktop: Found docker-desktop.
✔ Verify remote kubernetes status...done.
✔ Verify if nginx ingress is installed
↓ Installing nginx ingress [skipped]
→ Ngninx ingress is already setup.
✔ Verify domain is set... auto-assigning domain to 192.168.1.11.nip.io....set to 192.168.1.11.nip.io.
✔ 🏃‍  Running Helm to install Che
✔ Verify if helm is installed
✔ Check Helm …
```
=> feat(helm): Add support for helm v3

src/tasks/installers/helm.ts, test/tasks/installers/helm.test.ts
In V2 there are two versions, client and server and server version can lead to errors
```
Client: v2.13.0-rc.2+gb0d4c9e
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp [::1]:8080: connect: connection refused
```
so we stick to client only version
```
$ helm version -c --short
Client: v2.13.0-rc.2+gb0d4c9e
$ helm version -c --short
v3.0.0+ge29ce2a
```
Fixes https://github.com/eclipse/che/issues/15340
Change-Id: I0ca8ca68019aac5508079dc88f78aeff5cbdc142
=> fix(helm): Use client version all the time as server response may be unavailable on v2

src/api/che.ts, src/commands/workspace/inject.ts
Fixes looking for a workspace pod while `workspace:inject`.
closes https://github.com/eclipse/che/issues/14746
=> fix(inject): Rely on che.original_name label when looking for a workspace pod

src/commands/server/start.ts, src/commands/server/update.ts
Signed-off-by: Radim Hopp <rhopp@redhat.com>
Fixes renderer selection. Probably a typo from the time of creation of this repo.
So far only way to use/don't use the default renderer was to use/don't use interactive shell (tty).
Issue wasn't created for this AFAIK.
```
$ bin/run server:start --listr-renderer=verbose
[20:10:03] Verify Kubernetes API [started]
[20:10:03] Verify Kubernetes API...OK [title changed]
[20:10:03] Verify Kubernetes API...OK (it's OpenShift) [title changed]
[20:10:03] Verify Kubernetes API...OK (it's OpenShift) [completed]
[20:10:03] 👀  Looking for an already existing Che instance [started]
[20:10:03] Verify if Che is deployed into namespace "che" [started]
[20:10:03] Verify if Che is deployed into namespace "che"...it is not [title changed]
[20:10:03] Verify if Che …
```
=> Fix renderers.

README.md, src/api/kube.ts, src/commands/workspace/inject.ts
Adds the parameter `--context` to the `workspace:inject` command. It's used to specify the context to be injected. If no `--context` parameter is provided, the current context will be injected.
https://github.com/eclipse/che/issues/14877 (partly)
=> feat(inject): Allow to inject a kubeconfig with the specified context

.vscode/launch.json, README.md, bin/debug, src/api/che.ts, src/api/kube.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/workspace/inject.ts, src/commands/workspace/logs.ts, src/commands/workspace/start.ts, src/tasks/che.ts, src/tasks/installers/installer.ts, src/tasks/platforms/crc.ts, src/tasks/platforms/docker-desktop.ts, src/tasks/platforms/k8s.ts, src/tasks/platforms/microk8s.ts, src/tasks/platforms/minikube.ts, src/tasks/platforms/minishift.ts, src/tasks/platforms/openshift.ts, src/tasks/platforms/platform.ts, yarn.lock
1. Introduce a new command: `server:logs` to collect Eclipse Che logs (except workspace logs)
2. Introduce  `workspace:logs` to collect workspace log
3. Automatically collect logs when Eclipse Che is being installed
4. Automatically collect logs when Eclipse Che Workspace is being started
```
logs
|
-- <namespace>
|
-------- <pod>
|
----------- <container>.log
```
https://github.com/eclipse/che/issues/15485
=> feat: Collect logs during installation of Eclipse Che

README.md, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/workspace/logs.ts, src/tasks/che.ts, yarn.lock
This PR allows to store Eclipse Che logs into a system tmp directory by default
=> fix: Store server logs into system tmp directory by default

src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/workspace/logs.ts, yarn.lock
Use timestamp as a subfolder for Eclipse Che logs
=> fix: Use timestamp as a subfolder for Eclipse Che logs

README.md, src/api/kube.ts, src/commands/server/start.ts, src/tasks/installers/helm.ts, yarn.lock
Add ability to set up Che workspace and Postgres pvc class names using arguments.
https://github.com/eclipse/che/issues/15157
=> feat: Add ability to set up Che workspace and Postgres pvc class names using arguments.

README.md, src/api/che.ts, src/api/kube.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/workspace/logs.ts, src/tasks/che.ts, yarn.lock
Collect k8s events as well as che logs.
The project structure:
```
.
├── events.txt
├── mkdir-workspacet93uo90gd1acw8zj
│   └── mkdir-workspacet93uo90gd1acw8zj.log
├── workspacet93uo90gd1acw8zj.che-jwtproxy-6454d8877b-5xp26
│   └── verifier.log
└── workspacet93uo90gd1acw8zj.go-cli-bf5459458-fgrdx
├── che-machine-execrbr.log
├── go-cli.log
├── theia-ide3j0.log
└── vscode-goqsw.log
3 directories, 7 files
```
https://github.com/eclipse/che/issues/15604
=> feat: Collect k8s events

.github/CODEOWNERS
add nickboldt to CODEOWNERS to I can approve/merge https://github.com/che-incubator/chectl/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+chore dependabot PRs
Change-Id: I418668b78e6b04efeedf68b3e5ea82cbf5ab9ae7
=> feat: add nickboldt to CODEOWNERS

src/tasks/installers/helm.ts
Signed-off-by: Michal Vala <mvala@redhat.com>
Don't set namespace for workspaces when using helm installer. Helm charts already has reasonable default, which should be used and chectl should not interfere with it. Setting workspaces namespace can be implemented as new chectl parameter, but it's not in scope of this task.
https://github.com/eclipse/che/issues/15440
=> fix(helm): don't set workspace namespace for helm installer

src/api/kube.ts
Set tag from cheimage only for che-server.
https://github.com/eclipse/che/issues/14898
=> fix: Set tag from cheimage only for che-server.

.vscode/launch.json, README.md, src/api/version.ts, src/commands/server/start.ts, src/tasks/installers/helm.ts, src/tasks/platforms/crc.ts, src/tasks/platforms/docker-desktop.ts, src/tasks/platforms/k8s.ts, src/tasks/platforms/microk8s.ts, src/tasks/platforms/minikube.ts, src/tasks/platforms/minishift.ts, src/tasks/platforms/openshift.ts, test/api/version.test.ts, yarn.lock
Add minimal versions check for 
- openshift
- kubernetes
- helm
https://github.com/eclipse/che/issues/15680
=> feat: Add a chectl preflight check step that verifies that the platform version is supported

src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/logs.ts, src/tasks/platforms/api.ts, src/tasks/platforms/k8s.ts, yarn.lock
Move testApiTasks in a new ApiTask class to make it easier to sync in CRW downstream (as K8sTask is not present in it)
=> refactor: Separate testApiTasks to improve syncing with downstream

README.md, package.json, src/api/kube.ts, src/commands/server/start.ts, yarn.lock
Allows to override default values of custom resources by providing a patch file.
patch.yaml
```yaml
spec:
storage:
pvcStrategy: 'per-workspace'
```
```bash
chectl server:start  --che-operator-cr-patch-yaml=patch.yaml ....
```
https://github.com/eclipse/che/issues/15684
=> feat: Allows to override default values

src/api/kube.ts, src/tasks/installers/operator.ts
Don't wait keycloak pod if externalIdentityProvider is set
=> fix: Don't wait keycloak pod if externalIdentityProvider is set

package.json, src/commands/workspace/inject.ts, src/util.ts
Implements injection of Kubernetes config from host into Che workspace for Openshift infrastructure.
Also implements config injection for Openshift cluster with kubectl (yes, `kubectl` and `oc` is not interchangeable in all cases).
Start your cluster, deploy Che on it. When ready run the following command:
```sh
chectl workspace:inject -k -c <container-name>
```
If one wants to test specific CLI tool (`oc` or `kubectl`) with the cluster, then one need to remove other options from CLI list in `getClusterClientCommand` function in `src/util.ts` file.
To be able to test in some local clusters which has 'bad' TLS certificate, one need to relogin with `--insecure-skip-tls-verify` option and run `chectl` (as described above) before autologout. …
=> feat: Implement kube config injection on openshift cluster

yarn.lock
Set dependency on the latest version of che-operator and che
Fix PR check
=> fix: Set dependency on the latest version of che-operator and che

src/api/kube.ts, src/tasks/component-installers/cert-manager.ts
Fixes deployment of Cert Manager to be able to use Kubernetes v1.15.4 or older.
Tested with Kubernetes v1.12.0
=> fix: Improve deployment of Cert Manager to support older Kubernetes versions

src/commands/server/start.ts
Fixes condition which sets TLS by default flag, so it will not be forced for other than Helm installers any more.
=> fix: Fix non-Helm installers

.ci/cico_chectl_prcheck.sh, .ci/cico_common.sh, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, yarn.lock
Create setup scripts which execute e2e tests in minikube platform and also minishift. The basic e2e test cover the basic install of Eclipse Che without security enabled, Install che with multiuser enabled and auth.Also the test include the deletion of che deployments.
https://github.com/eclipse/che/issues/15815
=> fix: Run basic e2e tests on every PR.

.ci/cico_chectl_prcheck.sh, .ci/cico_common.sh
In ci.centos.org we are not available to install minikube because we are running under root user. 
Temporary remove to run minikube installation from e2e tests.
=> fix: Delete minikube e2e auto test temporary

src/tasks/che.ts
reuse this.devfileRegistrySelector and this.pluginRegistrySelector so we have fewer strings to replace in downstream
Change-Id: Ib8b63a2b225f4364a300d2e57eb15a401e53f497
=> fix: reuse variables so we have fewer strings to replace in downstream

src/commands/server/delete.ts
use consistent variable name for all minishiftAddonTasks
Change-Id: I86ea46af0218f4332e58a8ecefc820209eb2cb02
=> fix: use consistent variable name for all minishiftAddonTasks

src/api/kube.ts, src/commands/server/start.ts
Backports https://github.com/che-incubator/chectl/pull/561 to `7.9.x` branch
=> fix: Fall back to CR default value of tls support if tls flag is omitted

src/tasks/che.ts
fix deployment selections to use this.fooSelector instead of invalid selectors
Change-Id: Ie97fc3c6378e158032109ee6e4ee5e23053146ab
=> fix:  use this.fooSelector instead of invalid selectors

src/api/kube.ts
Uses default `che-tls` secret name for securing Che only if Che CR has no value specified.
https://github.com/eclipse/che/issues/16280
=> fix: Fallback to default Che tls secret only if CR has empty value for it

yarn.lock
Set dependencies to latest `che` and `che-operator`
=> fix: Update to latest che and che-operator

README.md, src/api/che.ts, src/commands/workspace/list.ts, src/tasks/che.ts
Add `workspace:list` command
```
✔ Verify Kubernetes API...OK
✔ Verify if namespace che exists
✔ Retrieving Eclipse Che server URL... http://che-che.192.168.99.100.nip.io
✔ Eclipse Che status check
✔ Get workspaces... done
Id      Name    Namespace       Status  Last modified
workspaceadm0rrdlo2kt9hj9	golang-5ssqg	che	STARTING	Wed Mar 11 2020 12:40:25 GMT+0200 (Eastern European Standard Time)
```
https://github.com/eclipse/che/issues/15071
=> feat: Add workspace:list command

README.md, src/api/che.ts, src/api/kube.ts, src/commands/workspace/delete.ts, src/commands/workspace/list.ts, src/tasks/che.ts, yarn.lock
Allows to delete user's workspace and namespace.
Use should have cluster admin rights to delete namespaces
```bash
$ ./run workspace:list -n abazkoche --access-token=$CHE_ACCESS_TOKEN
✔ Verify Kubernetes API...OK (it's OpenShift)
✔ Verify if namespace 'abazkoche' exists
✔ Retrieving Eclipse Che server URL... http://che-abazkoche.apps.ocp43.codereadyqe.com
✔ Eclipse Che status check
✔ Get workspaces... done
Id                        Name                          Namespace Status  Created                  Updated                  
workspace0kxaqsiwpe2h77g2 apache-camel-springboot-m83c3 admin-che STOPPED 2020-03-18T14:56:51.675Z                          
workspace8d7pzoq23h9iffiw golang-g2rp3                  admin-che STOPPED 2020-03-18T14:57:03.415Z 2020-03-18T14:57:05.404Z 
$ ./run …
```
=> feat: add workspace:delete command

package.json, src/api/che.ts, src/commands/workspace/create.ts, src/commands/workspace/start.ts, test/api/che.test.ts, yarn.lock
Adds new `workspace:create` command to `chectl`, which is supposed to replace `worspace:start` which become deprecated.
`workspace:create` command has `--start` option which starts the workspace right after creation.
In case of using `workspace:start` command, deprecation warning will be shown:
https://github.com/eclipse/che/issues/14344
=> feat: Add workspace:create command instead of workspace:start

README.md, src/commands/server/start.ts, src/tasks/installers/operator.ts, src/util.ts
Adds basic checks for TLS configuration of operator installer:
- For Kubernetes infrastructure family in case of TLS it is required to have pre-created secret. If it is not provided the expanded error message will be shown along with link to the corresponding docs section:
- Does basic check for `--self-signed-flag` option presence and automatically adds the flag if it is clear that self-signed certificate is used. However this check doesn't perform certificate analyzation directly, so it cannot catch all invalid cases, but only most frequent ones. I think that full certificate analyzation is out of scope of this PR, but left todo mark in the code.
Also corrects description for `--tls` flag.
https://github.com/eclipse/che/issues/16396
=> feat: Add basic TLS configuration checks

README.md, src/commands/server/start.ts
Adds clarification to `--domain` parameter of `server:start` command.
Adds warning message if `--domain` parameter is used with Openshift family infrastructures.
https://github.com/eclipse/che/issues/14404
https://github.com/eclipse/che/issues/16003
=> docs: Clarify '--domain' parameter in server:start command

src/commands/server/start.ts, src/tasks/platforms/common-platform-tasks.ts, src/tasks/platforms/k8s.ts, src/tasks/platforms/microk8s.ts, src/tasks/platforms/minikube.ts
Adds check whether Kubernetes cluster is reachable when installing Che.
The check could be disabled by `--skip-cluster-check` flag.
https://github.com/che-incubator/chectl/pull/613
=> feat: Add domain checks for Kubernetes family infrastructures

src/commands/server/start.ts, src/tasks/component-installers/cert-manager.ts
Adds functionality to print logs duplicates at the end of chectl output to avoid missing of the important messages by users.
Example with importing CA certificate:
https://github.com/eclipse/che/issues/16277
=> feat: Add ability to duplicate some messages at the end of chectl output

src/api/kube.ts, src/commands/server/update.ts, src/constants.ts, src/tasks/installers/operator.ts, yarn.lock
Allow to use domain flag for server:update command
=> fix: Reuse domain for server:update command

src/api/che.ts, src/api/kube.ts, src/commands/server/delete.ts, src/commands/server/update.ts, src/commands/workspace/inject.ts, test/api/che.test.ts, test/api/kube.test.ts, yarn.lock
Prints the current context when chectl is run
https://github.com/eclipse/che/issues/15741
=> feat: Print the current context when chectl is run

README.md, src/commands/server/start.ts, yarn.lock
chectl detects that local `templates` folder exists and tries to copy resources from it. But if it just an arbitrary folder of any project then chectl fails. PR adds additional check that templates` folder should contain `che-operator` or `minishift-addon` subfolder depending on installer type.
https://github.com/eclipse/che/issues/16555
=> fix: Ignores templates folder if it doesn't contain che-operator templates

README.md, src/commands/server/start.ts, src/tasks/installers/operator.ts
Fixes links to Che installation with self-signed certificates docs.
https://github.com/eclipse/che/issues/16682
=> docs: Fix links to Che installation docs

README.md, src/commands/dashboard/open.ts, yarn.lock
Add `dashboard:open`  command to open Che dashboard
https://github.com/eclipse/che/issues/15003
=> feat: Add dashboard:open command

src/api/kube.ts
Fix the message to print current k8s context
```bash
$ ./run workspace:list
› Current kuberntetes context: 'minikube'
Id                        Name Namespace Status  Created                  Updated  
...
```
=> fix: Use the correct message to print the current k8s context

yarn.lock
Updates yarn.lock, so chectl uses latest operator version (templates from it)
https://github.com/eclipse/che/issues/16798
=> fix: Update yarn.lock to use latest operator templates

src/api/kube.ts, src/tasks/installers/common-tasks.ts
If user deploys Che using chectl with default CR and OAuth is not enabled, force user to change Che admin password from default `admin:admin` on first login.
https://github.com/eclipse/che/issues/14082
=> feat: Force user to change default Che admin password after first login

README.md, src/commands/cacert/export.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/create.ts, src/commands/workspace/delete.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/logs.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts, src/common-flags.ts, src/tasks/platforms/api.ts, src/tasks/platforms/docker-desktop.ts, src/tasks/platforms/k8s.ts, yarn.lock
Add `--skip-kubernetes-health-check` flag to bypass k8s health check.
https://github.com/eclipse/che/issues/15331
=> feat: Add flag to skip health check

src/api/kube.ts
Move applying CR patch for operator installer after predefined CR corrections on chectl side.
=> fix: Apply CR patch after all manipulations

yarn.lock
Update che-operator and che versions
=> fix: Update che-operator and che versions

README.md, src/api/kube.ts, src/api/version.ts, src/commands/server/start.ts, src/commands/server/update.ts, src/util.ts, yarn.lock
Use olm installer by default for OpenShift 4
https://github.com/eclipse/che/issues/16861
=> feat: Use olm installer by default for OpenShift 4

src/tasks/installers/common-tasks.ts, src/tasks/installers/installer.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, yarn.lock
Using 'openshift-marketplace' for `catalogSourceNamespace` for OpenShift platform familiy
https://github.com/eclipse/che/issues/16913
=> fix: Use 'openshift-marketplace' for OpenShift platform familiy

src/commands/server/start.ts, src/commands/server/update.ts, src/tasks/installers/common-tasks.ts, src/tasks/platforms/common-platform-tasks.ts, src/tasks/platforms/crc.ts, src/tasks/platforms/minishift.ts, src/tasks/platforms/openshift.ts, yarn.lock
Makes oAuth configuration checker run only if `server:start` or `server:update` command is used.
=> fix: Check for oAuth platform configuration only on server start and update

src/commands/server/start.ts, src/commands/server/update.ts, src/tasks/che.ts, src/tasks/installers/olm.ts, src/util.ts
Check if subscription exists and automatically set installer type to `olm` if it wasn't specified.
https://github.com/eclipse/che/issues/16861
=> fix: Detect olm installer type for server:update command

yarn.lock
Update yarn.lock to the latest che-operator commit
https://github.com/eclipse/che/issues/16959
=> fix(yarn.lock): Update the operator to latest upstream commit

src/commands/server/start.ts
Allow to use os-oauth with olm installer
https://github.com/eclipse/che/issues/16969
=> fix(olm): Allow to use os-oauth with olm installer

.travis.yml
This PR fix binaries for OSX by adding to `npx oclif-dev pack` command all archs including s390x.
https://github.com/eclipse/che/issues/16801
=> fix: Fix chectl package

src/api/che.ts, src/api/kube.ts, src/commands/server/update.ts, src/constants.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/operator.ts, yarn.lock
In general the CR name in the namespace should not be `eclipse-che`.
This PR don't stick to `eclipse-che` as a CR name.
https://github.com/eclipse/che/issues/16966
=> fix: Don't stick to eclipse-che as a CR name

installers/cert-manager.yml
Signed-off-by: Prabhav Thali <Prabhav.Thali1@ibm.com>
Upgrade cert-manager from `v0.12.0` to `v0.15.0` as `v0.15.0` cert-manager images have multi-arch support.
This PR is part of [this ](https://github.com/eclipse/che/issues/16655)initiative.
=> chore(deps-dev): Adding s390x support to chectl

src/api/kube.ts, yarn.lock
Sometimes pod `status` might not contain `condition` of type `Ready`.
It is better to return `underfine` for getPodReadyConditionStatus and allows other function to wait and get `condition` in the next request.
https://github.com/eclipse/che/issues/17001
=> fix: Improve getPodReadyConditionStatus

README.md, src/api/kube.ts, src/commands/server/delete.ts, src/commands/server/stop.ts, src/tasks/che.ts, yarn.lock
Wait until pods are actual deleted for server:delete and server:stop commands
https://github.com/eclipse/che/issues/14595
=> fix: Wait until pod is actual deleted for server:delete and server:stop commands

.vscode/launch.json, README.md, src/commands/cacert/export.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts
Removes platform flag from `cacert:export` command
=> chore(cacert:export): Remove platform flag from cacert:export command

README.md, src/api/che.ts, src/api/kube.ts, src/commands/cacert/export.ts, src/commands/server/start.ts, src/tasks/component-installers/cert-manager.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/helm.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, yarn.lock
Deprecates `self-signed-cert` option of `server:start` command.
In case of Operator installer this is handled on operator side, see https://github.com/eclipse/che-operator/pull/285
In case of Helm installer, chectl checks whether `self-signed-certificate` secret exists and based on that makes conclusion if self-signed certificate is used and put the value into Helm chart.
Issue: https://github.com/eclipse/che/issues/16764
Depends on: https://github.com/eclipse/che/pull/17044 and https://github.com/eclipse/che-operator/pull/285
Tested on:
- Minikube (Operator and Helm installers)
- CRC (Operator installer)
- Openshift (Operator installer with oAuth)
- Openshift (OLM installer)
=> feat: Deprecate 'self-signed-cert' flag and implement autodetection for it

src/commands/server/start.ts
Openshift 4.1 doesn't have OLM from the box. So let's check if OLM is preinstalled.
Part of the https://issues.redhat.com/browse/CRW-967
=> fix: Check if Olm is preinstalled on the Openshift 4.

README.md, src/commands/server/start.ts, src/tasks/installers/olm.ts
Add catalog source name and namespace to use external catalog source to install Eclipse Che. It is possible way how test nightly or release candidates.
For example nightly preview operatorSource:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
namespace: openshift-marketplace
spec:
authorizationToken: {}
endpoint: 'https://quay.io/cnr'
registryNamespace: eclipse-che-operator-openshift
type: appregistry
```
Apply it:
```
$ kubectl apply -f operatorSource.yaml -n openshift-marketplace
```
And install nightly Che:
```
chectl server:start -p openshift -n moon44 --catalog-source-name=eclipse-che-preview-openshift --catalog-source-namespace=openshift-marketplace --olm-channel=nightly …
```
=> feat: Add catalog source name and namespace to use external catalog source to install Eclipse Che.

README.md, src/commands/server/start.ts, src/tasks/installers/olm.ts
Add catalog source name and namespace to use external catalog source to install Eclipse Che. It is possible way how test nightly or release candidates.
For example nightly preview operatorSource:
```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
namespace: openshift-marketplace
spec:
authorizationToken: {}
endpoint: 'https://quay.io/cnr'
registryNamespace: eclipse-che-operator-openshift
type: appregistry
```
Apply it:
```
$ kubectl apply -f operatorSource.yaml -n openshift-marketplace
```
And install nightly Che:
```
chectl server:start -p openshift -n moon44 --catalog-source-name=eclipse-che-preview-openshift --catalog-source-namespace=openshift-marketplace --olm-channel=nightly …
```
=> feat: Add catalog source name and namespace to use external catalog source

src/api/kube.ts, src/tasks/platforms/minikube.ts
Minikube starting from version `1.9` has [a bug](https://github.com/kubernetes/minikube/issues/7218) which prevents Che and some other products from successful deployment. The root cause is the outdated storage-provisioner image and updating it to the latest version fixes the problem, but it also requires to add some permissions to the storage-provisioner cluster role. That is done in this PR on platform preparation phase.
However, we should update range of Minikube versions for which this workaround is applied when Minikube with the fix released.
Tested with Minikube 1.11.0
https://github.com/eclipse/che/issues/17142
=> fix: Add workaround for Minikube storage provisioning bug

yarn.lock
Update che-operator dependencies
=> chore(yarn.lock): Update che-operator dependencies

src/tasks/installers/helm.ts
Sets `global.tls.useSelfSignedCerts` flag only if `self-signed-certificate` secret exists
https://github.com/eclipse/che/issues/17333
=> fix: (helm) Fix selfSignedCert detection for helm installer

test/e2e/minishift.test.ts
Sometimes the jobs crash with the next error:
`Timeout - Async callback was not invoked within the 600000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 600000ms timeout specified by jest.setTimeout.Error: `
Execute `server:start` test case using execa library.
=> fix: Fix minishift server:start test case

src/api/kube.ts, yarn.lock
`server:delete` command should not throw an error trying to remove `checlusters` CR when Eclipse Che has been deploying using helm.
https://github.com/eclipse/che/issues/17375
=> fix: Don't throw an error when there is no checlusters crd

README.md, src/api/kube.ts, src/commands/server/start.ts, src/tasks/platforms/common-platform-tasks.ts, test/e2e/util/cr-test.yaml, yarn.lock
- removes `os-oauth` flag (OpenShift OAuth is turned on by default)
More details in https://www.eclipse.org/lists/che-dev/msg03867.html
https://github.com/eclipse/che/issues/17488
=> feat: Setup OpenShift OAuth by default on OpenShift infrastructure

yarn.lock
Updates operator dependency after https://github.com/eclipse/che-operator/pull/380
https://issues.redhat.com/browse/CRW-1022
=> chore(yarn.lock): Update operator dependency

src/commands/server/delete.ts, src/commands/server/stop.ts, src/tasks/che.ts
This PR allows to delete Eclipse Che despite the fact that it isn't available (Che API doesn't respond). 
https://github.com/eclipse/che/issues/17534
=> fix: Allows to delete Eclipse Che even if server isn't available

src/api/kube.ts, src/tasks/installers/operator.ts
Deletes CRD only if there no another checluster CR
https://github.com/eclipse/che/issues/16000
```
Existed Eclipse Che operator: quay.io/eclipse/che-operator:7.18.0.
New Eclipse Che operator    : che-operator:latest.
›   Warning: This command updates Eclipse Che to 7.18.0 version, but custom operator image is specified.
›   Warning: Make sure that the new version of the Eclipse Che is corresponding to the version of the tool you use.
›   Warning: Consider using 'chectl update [stable|next]' to update to the latest version of chectl.
If you want to continue - press Y:
```
=> fix: Don't remove CRD if another deployments found

src/commands/server/update.ts, src/util.ts
Provides more information to a user before before updating Eclipse Che
https://issues.redhat.com/browse/CRW-1175
=> chore: Make server:update command more informative

src/constants.ts
Fixes link to doc about importing CA into browser, which was broken by https://github.com/eclipse/che-docs/pull/1451
=> fix: Fix link to doc about importing CA into browser

src/commands/server/start.ts
Sometimes chectl fails before Che pods start and that means there are not any logs. 
This PR check if directory logs are empty and print a message.
https://issues.redhat.com/browse/CRW-859
=> fix: Fix chectl logs before che pods start

.vscode/launch.json, README.md, src/api/kube.ts, src/commands/server/delete.ts, src/tasks/che.ts, src/tasks/installers/operator.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, test/e2e/openshift.test.ts
This PR have:
- New flag(--delete-namespace) for server:delete which allows users to delete the namespace after remove Che resources from cluster
- Remove ConsoleLinks from cluster 
- Remove all oauthClientAuthorizations linked to che instance
https://issues.redhat.com/browse/CRW-714
https://github.com/eclipse/che/issues/17784
=> feat: Rework server:delete to remove consoleLinks, namespace or openshift oauthAuthorizations

src/tasks/installers/operator.ts
After installing Eclipse Che using `helm`, server:delete is not working properly because no CRD are created.
Log issue:
[flacatus@chehost-local chectl]$ ./bin/run server:delete
› Current Kubernetes context: 'minikube'
You're going to remove Eclipse Che server in namespace 'che' on server 'https://172.17.0.10:8443'. If you want to continue - press Y: y
✔ Verify Kubernetes API...OK
✔ Delete oauthClientAuthorizations...OK
✔ Delete the Custom Resource of type checlusters.org.eclipse.che...OK
✖ Delete CRD checlusters.org.eclipse.che
→ customresourcedefinitions.apiextensions.k8s.io "checlusters.org.eclipse.che" not found
Delete role binding che-operator
Delete role che-operator
Delete cluster role binding che-che-operator
Delete cluster role …
=> fix: Fix server:delete when installer was helm

package.json, src/tasks/installers/olm.ts
nightly has strong tendentious to breaking changes. It would be nice to enable auto-update for nightly channel to sync images changes with deployment and permission changes in the csv file.
none. Enhancement.
=> feat: Use automatic update for nightly olm installer.

package.json, src/api/che.ts, src/api/kube.ts, src/commands/devfile/generate.ts, test/api/kube.test.ts, yarn.lock
Update the K8s javascript library
It's because it's somehow failing when using some devworkspace yamls
(seems that moving to 0.12.0 is not possible as a delete operation is not there https://github.com/kubernetes-client/javascript/issues/491)
N/A
Change-Id: I32bc71dcdce66b4b61184f8a07e638c70fc9a1b4
=> feat(k8s-client): Bump the client from 0.10.2 to 0.11.2

package.json, src/api/kube.ts, yarn.lock
Bump kubernetes-javascript lib dependency to 0.12.1
Also add new transitive dependency that is missing in k8s-client else tests are failing
When I did a previous PR, 0.12.0 was failing but now they've released 0.12.1 !
https://github.com/che-incubator/chectl/pull/858
Change-Id: I6e61384abc8f0f7a8753eed6b6f52eab529022a6
=> feat(k8s-client): Bump dependency to 0.12.1

package.json, src/api/che.ts, src/commands/cacert/export.ts, src/tasks/che.ts, yarn.lock
Fixes `cacert:export` command to save only CA certificate from the certificate chain of the `self-signed-certificate` secret.
https://github.com/eclipse/che/issues/16773
=> feat: Make cacert export save only CA certificates

src/tasks/platforms/minikube.ts
In the latest versions of Minikube enabling of ingress addon takes more time than in previous versions. Because of that, chectl fails on the addon enabling step. Thsi PR increases the timeout to avoid such installation failure.
https://github.com/eclipse/che/issues/17952
=> fix: Increase Minikube ingress addon enabling timeout

src/api/kube.ts, yarn.lock
Sometimes chectl fails to deploy Eclipse Che because several keycloak pods are present.
This PR should solve this problem.
=> fix: Do not throw error if several pods are found

.github/workflows/e2e.yml, README.md, src/api/che-api-client.ts, src/api/kube.ts, src/api/version.ts, src/commands/server/status.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, test/e2e/openshift.test.ts
This PR add a new command to chectl which prints some information about che instance: if Openshift Oauth is enabled, version, che url or how many workspaces exist.
Also this PR rename the variable of minishift e2e job (GITHUBTOKEN--> GITHUB_TOKEN)
https://github.com/eclipse/che/issues/14476
=> feat: Create new chectl command -> server:status

.github/PULL_REQUEST_TEMPLATE.md
Add the new PR Template
https://github.com/eclipse/che/issues/17486
=> chore(github): Update the pull request template to match new definition of done on PR

src/tasks/platforms/microk8s.ts
Explicitly specify microk8s.status output format (--format short) since microk8s recently changed the default format (with v 1.19.0), breaking the addons enabled preflight checks.
https://github.com/eclipse/che/issues/16408
Using chectl with microk8s platform, where microk8s version is 1.19.0 or later, prior to fix, it will incorrectly fail on the MicroK8s preflight checklist, with the Error "The storage addon hasn't been enabled in microk8s". 
After the fix, the preflight checks for storage and ingress addons enabled will succeed.
=> fix: Explictly specify microk8s.status output format

src/commands/cacert/export.ts, src/commands/dashboard/open.ts, src/commands/devfile/generate.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/create.ts, src/commands/workspace/delete.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/logs.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts
add explicit flag type annotations per https://github.com/microsoft/TypeScript/issues/29221 to fix downstream build
Change-Id: I9eee44451b2ed41382cda9a446c47fc5c8f39e33
=> fix: add explicit flag type annotations per microsoft/TypeScript#29221 to fix downstream build

README.md
Update manual install steps
https://github.com/eclipse/che/issues/17823
Try to install chectl following the manual steps
=> fix(REAME.md): Update manual install steps

src/tasks/che.ts, src/tasks/component-installers/cert-manager.ts, src/tasks/installers/common-tasks.ts
Reorders post-installation messages.
```
✔ Show important messages
✔ Eclipse Che 7.21.0-SNAPSHOT has been successfully deployed.
✔ Documentation             : https://www.eclipse.org/che/docs/
✔ 
✔ Users Dashboard           : https://che-che.192.168.99.100.nip.io
✔ Admin user login          : "admin:admin". NOTE: must change after first login.
✔ 
✔ Plug-in Registry          : https://plugin-registry-che.192.168.99.100.nip.io/v3
✔ Devfile Registry          : https://devfile-registry-che.192.168.99.100.nip.io
✔ 
✔ Identity Provider URL     : https://keycloak-che.192.168.99.100.nip.io/auth
✔ Identity Provider login  : "admin:xNbVw8DMYjz1".
✔ 
✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: …
```
=> fix: Reorder messages

src/api/che.ts, src/commands/cacert/export.ts
Links exported certificate to a platform
```
./run cacert:export
› Current Kubernetes context: 'minikube'
Eclipse Che self-signed CA certificate is exported to /tmp/cheCA.crt
```
1. build the project
2. Deploy Eclipse Che
2. `bin/run cacert:export`
=> feat: Store cheCA.crt file into tmp directory

src/commands/server/deploy.ts
Fix appearing `serverstart` command deprectation note
Little quick fix
Run:
```
./bin/run server:deploy -n che -p openshift -m
```
Message:
`Warning: 'server:start' command is deprecated. Use 'server:deploy' `
should not appear.
=> fix: Fix appearing server start deprectation note

src/api/che-login-manager.ts
Fixes case when user home on *nix systems doesn't have `.config` directory created.
https://github.com/eclipse/che/issues/18169
Run `chectl auth:login <args>` command 
=> fix: Handle case when '~/.config' dir is missing

.vscode/tasks.json, src/api/kube.ts, src/api/typings/olm.d.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/common-flags.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, src/tasks/platforms/common-platform-tasks.ts, src/util.ts
Use Olm CR sample from CSV
None. Code enhancement.
Install Che on the Openshift platform:
```bash
$ chectl server:start -n che -p openshift -m
```
Take a look on the CR:
```bash
$ oc get checluster eclipse-che  -n che -o  yaml
```
Check Che using url. 
And also make sure that operator installer still works too:
```bash
$ chectl server:start -n che2 -p openshift -m --installer operator
```
=> fix: Use Olm CR sample from CSV

src/tasks/platforms/minikube.ts
Patch minikube storage only for 1.9.1...1.12.1 versions
https://github.com/eclipse/che/issues/18228
1. Deploy Eclipse Che on minikube 1.12.1 and latest versions
2. Check that patch is applied only for minikube 1.12.1
=> fix: Patch minikube storage only for 1.9.1...1.12.1 versions

README.md, src/api/kube.ts, src/api/openshift.ts, src/api/version.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/deploy.ts, src/commands/server/logs.ts, src/commands/server/status.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/common-flags.ts, src/constants.ts, src/tasks/che.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/minishift-addon.ts, src/tasks/installers/operator.ts, src/tasks/kube.ts, src/tasks/platforms/api.ts, src/tasks/platforms/common-platform-tasks.ts, src/tasks/platforms/openshift.ts, src/util.ts, test/e2e/minikube.test.ts, test/e2e/minishift.test.ts, test/e2e/openshift.test.ts, test/tasks/platforms/openshift.test.ts
- initialize context for all commands in the same way
- fix 'openshift is running` check to run `oc status` for default namespace
- add `-y` flag for confirmation, others flag marked as hidden.
- make `server:update` command platform independent (the corresponding flags are hidden)
=> fix: chectl improvements

src/api/kube.ts, src/api/typings/olm.d.ts, src/tasks/installers/olm.ts
1. Fix catalog source yaml argument for olm installer. 
2. Fix timeout installation error, when install plan installs longer than 30 sec. It's reproducible with cluster bot on first installation. Second installation is much faster and bug is not reproducible. Fix important for CRW.
https://github.com/eclipse/che/issues/18105
**Test fix timeout error:**
1. Request cluster using bot.
2. Install Che first time:
```bash
$ ./bin/run server:start -n che -p openshift -m
```
This first installation could fail. With this fix it should not.
**Test catalogsource yaml argument:**
1. Create file with custom catalog source yaml:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
namespace: che
spec:
sourceType: grpc
image: …
```
=> fix: Fix catalog yaml argument

src/api/kube.ts, src/api/typings/olm.d.ts, src/tasks/installers/olm.ts
Backport to branch 7.20.x
1. Fix catalog source yaml argument for olm installer. 
2. Fix timeout installation error, when install plan installs longer than 30 sec. It's reproducible with cluster bot on first installation. Second installation is much faster and bug is not reproducible. Fix important for CRW.
https://github.com/eclipse/che/issues/18105
**Test fix timeout error:**
1. Request cluster using bot.
2. Install Che first time:
```bash
$ ./bin/run server:start -n che -p openshift -m
```
This first installation could fail. With this fix it should not.
**Test catalogsource yaml argument:**
1. Create file with custom catalog source yaml:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
namespace: che
spec:
sourceType: …
```
=> fix: Backport fix catalog yaml argument and first installation timeout issue

src/commands/server/deploy.ts
This PR fix a bug when `--installer` flag is not defined. By default installer now is `olm`. I moved the suggested namespace check after `setPlaformDefaults` function.
=> fix: Fix --olm-suggested-namespace flag when --installer flag is absent

src/api/che-login-manager.ts, src/commands/auth/login.ts, src/commands/workspace/create.ts, src/commands/workspace/delete.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts, yarn.lock
It makes workspace commands works for single-user mode
https://github.com/eclipse/che/issues/18406
1. Deploy Eclipse che in single-user mode `chectl server:deploy --platform minikube --installer helm`
2. Use workspace commands
=> fix: Make workspace commands works for single-user mode

README.md, src/commands/server/deploy.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/common-flags.ts, src/tasks/che.ts, src/util.ts, yarn.lock
Split functionality between server:deploy and server:star commands
```
./run server:start    
› Current Kubernetes context: 'minikube'
✔ Verify Kubernetes API...OK
✔ 👀  Looking for an already existing Eclipse Che instance
✔ Verify if Eclipse Che is deployed into namespace "che"...it is not
›   Warning: Eclipse Che has not been deployed yet. Use server:deploy command to deploy a new Eclipse Che instance.
```
```
./run server:deploy --platform minikube   --che-operator-cr-patch-yaml ~/Documents/noupdatepassword.yaml 
› Current Kubernetes context: 'minikube'
› Installer type is set to: 'operator'
✔ Verify Kubernetes API...OK
✔ 👀  Looking for an already existing Eclipse Che instance
✔ Verify if Eclipse Che is deployed into namespace "che"
✔ Found running Eclipse Che deployment
✔ Found running …
```
=> feat: Split functionality between server:deploy and server:star commands

README.md, src/api/kube.ts, src/common-flags.ts, src/constants.ts, yarn.lock
Fixes usage of constants that define some kubernetes client timeouts
N/A
Should fix https://github.com/eclipse/che/issues/18464
1. Perform `yarn pack`
2. Unpack the archive into a separate folder
3. Run chectl
=> Fix default timeout constants

src/api/che.ts, src/api/kube.ts, src/commands/cacert/export.ts, src/commands/server/deploy.ts, src/commands/workspace/delete.ts, src/tasks/che.ts, src/tasks/component-installers/cert-manager.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/helm.ts, test/api/che.test.ts
- removes duplication in post-installation output
- waits workspace active state after creation
https://github.com/eclipse/che/issues/18413
https://github.com/eclipse/che/issues/18416
=> fix: Wait namespace active state

src/tasks/che.ts
N/A
https://github.com/eclipse/che/issues/18421
1. Deploy Eclipse Che using Helm installer: `chectl server:deploy --platform=minikube --multiuser --installer=helm`
2. Login: `chectl auth:login -u admin -p admin`
3. Stop Che: `chectl server:stop`
4. Stop Che again: `chectl server:start`
=> Handle dashboard pod on server start/stop commands

src/api/context.ts, src/commands/server/update.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, src/util.ts, tsconfig.json, yarn.lock
Improve messages in server:update command
```
Existed Eclipse Che operator: quay.io/eclipse/che-operator:nightly.
New Eclipse Che operator    : quay.io/eclipse/che-operator:nightly.
›   Warning: 'chectl' tool is not up to date.
›   Update 'chectl' first: 'chectl update next' and then try again.
If you want to continue - press Y:
```
```
Existed Eclipse Che operator: quay.io/eclipse/che-operator:nightly.
New Eclipse Che operator    : quay.io/eclipse/che-operator:nightly.
Eclipse Che is already up to date.
```
```
Existed Eclipse Che operator: quay.io/eclipse/che-operator:nightly.
New Eclipse Che operator    : docker.io/abazko/operator:local.
›   Warning: Eclipse Che operator deployment will be updated with the provided image,
›   but other …
```
=> feat: Improve messages in server:update command

README.md, src/commands/server/deploy.ts, src/tasks/installers/helm.ts
Passes file provided by `--helm-patch-yaml` flag as a `values.yaml` parameter for Helm Chart.
Provided command line arguments oc chectl take precedence over the patch values.
N/A
https://github.com/eclipse/che/issues/18459
1. Create `helm-patch.yaml` file with some corrections, for example:
```yaml
global:
cheWorkspacesNamespace: che-ws-<username>
```
2. Deploy Eclipse Che using Helm installer with the patch:
```sh
chectl server:deploy --platform=minikube --installer=helm --multiuser --helm-patch-yaml=helm-patch.yaml
```
3. Check that patch is applied (start a workspace and check the k8s namespace of it)
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-an …
=> fix: Use -f with yaml of helm patch

src/api/kube.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/tasks/platforms/common-platform-tasks.ts
Remove not actual openshift oAuth auto detection.
https://issues.redhat.com/browse/CRW-1361
You need to install Eclipse Che on the openshfit 4 with no identity providers. Message about `OpenShift OAuth is turned off` shouldn't appear.
=> fix: Remove not actual openshift oAuth auto detection.

src/api/kube.ts, src/constants.ts, src/tasks/component-installers/cert-manager.ts
Makes chectl to select Cert-Managers's ClusterIssuer by label instead of creating own one.
The new behaviour:
1. Try to get ClusterIssuer by label
2. If there is only one ClusterIssuer found - use it, if more than one - fail with error message
3. If no ClusterIssuer with corresponding label found, create own one (as was done before in all cases)
https://github.com/eclipse/che/issues/18450
1. Install Cert-Manager
2. Configure ClusterIssuer
3. Label the ClusterIssuer with `app=che` label
4. Deploy Eclipse Che with Helm installer
5. It should use already existing ClusterIssuer instead of creating own
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-c …
=> fix: [Helm] Select ClusterIssuer by label

src/commands/cacert/export.ts, src/commands/dashboard/open.ts, src/commands/devfile/generate.ts, src/commands/server/debug.ts, src/commands/server/logs.ts, src/commands/server/status.ts, src/commands/workspace/create.ts, src/commands/workspace/delete.ts, src/commands/workspace/inject.ts, src/commands/workspace/list.ts, src/commands/workspace/logs.ts, src/commands/workspace/start.ts, src/commands/workspace/stop.ts
Showing notification on every command annoys. Commands which can be finished in a few seconds like dashboard:open and server:status should not have notification. This PR removes completion notification for some commands. 
https://github.com/eclipse/che/issues/18702
=> chore: Remove notification for some commands

test/e2e/e2e.test.ts, yarn.lock
Update dependencies.
https://github.com/eclipse/che/issues/18754
=> chore(yarn.lock): Update dependencies

src/tasks/installers/olm.ts
When olm is installer by default now we are replacing CSV image with default one. 
This PR replace the image only if it is specify with flag `--che-operator-image`
Ref issue: https://issues.redhat.com/browse/CRW-1512
=> fix: Fix che operator image patch when installer is olm

src/api/version.ts, src/commands/server/deploy.ts, src/hooks/prerun/new-version-warning.ts, src/tasks/installers/common-tasks.ts, src/util.ts
Fixes path to templates folder in case of running chectl from installation directory.
Improves some messages according to suggestions from UX team.
https://github.com/eclipse/che/issues/19019
1. Build and pack chectl
2. Install chectl into a folder
3. Try to deploy Che using the chectl
=> Fix path to templates folder in case of running chectl from installation directory

src/api/context.ts, src/api/version.ts, src/constants.ts, src/hooks/prerun/new-version-warning.ts, src/util.ts
Replaces `chectl` string usage by corresponding constant.
https://github.com/eclipse/che/issues/18022
N/A refactoring
=> refactor: Move chectl project name into a separate constant

src/api/version.ts
Handle corrupted update file
https://github.com/eclipse/che/issues/19033
- Create corrupted `next-update-info.json` in `~/.cache/chectl`
- Try to deploy Eclipse Che
=> fix: Handle corrupted update file

src/tasks/che.ts
Print HTPasswd user credentials when Eclipse Che provisions OpenShift OAuth user.
```
✔ Users Dashboard           : https://che-eclipse-che.apps.abazko.devcluster.openshift.com
✔ HTPasswd user credentials : "che:O3KIan".
```
https://github.com/eclipse/che/issues/18152
=> chore: Print HTPasswd user credentials

.github/workflows/e2e-minikube-operator-update.yml, test/e2e/e2e-upgrade.test.ts, test/e2e/util.ts
Adds new PR check that tests Che update flow using `operator` installer.
The test does the following:
1. Deploys latest stable version of Che.
2. Creates a workspace, starts (waits for `RUNNING` state) and then stops it.
3. Updates Che to nightly version (the one under development).
4. Starts the workspace to check that nothing is wrong with old workspaces.
5. Downgrades Che back to the latest stable version.
https://github.com/eclipse/che/issues/19013
Run 
```sh
minikube start && minikube addons enable ingress
yarn test --coverage=false --forceExit --testRegex=test/e2e/e2e-upgrade.test.ts
```
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-check …
=> chore: Add Che update e2e test

src/tasks/installers/operator.ts
Wait until operator remove cluster scope objects itself
https://github.com/eclipse/che/issues/18501
1. deploy eclipse-che  on OpenShift
2. run `server:delete` make sure when checluster is removed then all cluster scope objects are removed as well
=> fix: Wait until operator remove cluster scope objects itself

src/api/version.ts, src/commands/server/deploy.ts, src/commands/server/update.ts, src/tasks/installers/helm.ts
If  `next-update-info.json` contains some invalid version under `latestVersion` field then chectl fails on checking update.
This PR is intended to fix the problem by catching version comparison and providing default behavior for such cases. 
https://github.com/eclipse/che/issues/19562
1. Update `next-update-info.json`: `{"latestVersion":"undefined","lastCheck":1618297305982}`
2. Try server:deploy command
=> fix: Don't fail on version comparison 

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release-build-and-push-to-GH-releases.yml, CONTRIBUTING.md, README.md, make-release.sh, package.json, yarn.lock
Che operator and chectl was already migrated from master to main branch.
Ref issue: https://github.com/eclipse/che/issues/19410
=> chore: References from `master` to `main` branches

package.json, yarn.lock
Update operator templates after https://github.com/eclipse-che/che-operator/pull/684
=> Update operator templates

src/tasks/installers/operator.ts
Use crd v1beta1 if kubernetes doesn't support v1
https://github.com/eclipse/che/issues/19648
=> fix: Use crd v1beta1 if kubernetes doesn't support v1

src/tasks/installers/operator.ts
Deploys `CheClusterBackup` and `CheClusterRestore` CRDs if available in templates.
Just deploy Che
=> Apply backup/restore CRDs if available

src/tasks/installers/operator.ts
Fixes Che update when backup/restore CRDs are missing in install templates.
Follow-up fix for: https://github.com/che-incubator/chectl/pull/1253
Update Eclipse Che when ackup/restore CRDs are not in installation templates.
=> fix: Fix Che update when backup/restore CRDs don't exist

src/tasks/kube.ts
- Inspect checluster status and fail if status.reason is not empty (when there is an error on operator side)
```
❯ Operator pod bootstrap
✖ Scheduling...failed
→ Eclipse Che operator failed, reason: Fail, message: Fail for some reason. Consider increasing error recheck timeout with --k8spoderrorrechecktimeout flag.
Downloading images
Starting
Prepare Eclipse Che cluster CR
›   Error: Error: Eclipse Che operator failed, reason: Fail, message: Fail for some reason. Consider increasing error recheck timeout with --k8spoderrorrechecktimeout flag.
›   Command server:deploy failed. Error log: /home/tolusha/.cache/chectl/error.log
```
https://github.com/eclipse/che/issues/19284
1. Deploy Eclipse Che using custom operator image with setting not …
=> feat: Inspect checluster status and fail if status.reason is not empty

src/api/che-api-client.ts, src/api/kube.ts, src/commands/auth/login.ts, src/commands/cacert/export.ts, src/commands/server/debug.ts, src/commands/server/delete.ts, src/commands/server/deploy.ts, src/commands/server/logs.ts, src/commands/server/start.ts, src/commands/server/stop.ts, src/commands/server/update.ts, src/commands/workspace/inject.ts, src/tasks/che.ts, src/tasks/installers/helm.ts, src/tasks/platforms/api.ts, src/tasks/platforms/docker-desktop.ts, src/tasks/platforms/k8s.ts, src/util.ts, test/e2e/e2e.test.ts, test/e2e/util.ts
- Improve error handling all over the code
- Got read of possible `cannot read property 'statusCode' of undefined` error
```bash
2021-06-03T14:59:23.714Z Error: Command server:deploy failed. Error log: /home/tolusha/.cache/chectl/error.log.
2021-06-03T14:59:23.715Z     at newError (~/projects/chectl/src/util.ts:201:17)
2021-06-03T14:59:23.715Z     at Object.wrapCommandError (~/projects/chectl/src/util.ts:197:10)
2021-06-03T14:59:23.715Z     at Deploy.<anonymous> (~/projects/chectl/src/commands/server/deploy.ts:447:18)
2021-06-03T14:59:23.715Z     at Generator.throw (<anonymous>)
2021-06-03T14:59:23.715Z     at rejected (~/projects/chectl/src/commands/server/deploy.ts:15:65)
2021-06-03T14:59:23.715Z Cause: Error: 404 page not found …
```
=> chore: Improve error handling

src/tasks/component-installers/devfile-workspace-operator-installer.ts
This PR add a fix to remove completelly webhooks configurations when DWO will be uninstalled.
https://issues.redhat.com/browse/CRW-1930
=> fix: Remove devworkspace validating webhook configuration from cluster if dwo will be uninstalled

src/tasks/installers/operator.ts
Applies `CheBackupServerConfiguration` CRD if available when deploying Che
N/A
https://github.com/eclipse/che/issues/19977
Deploy Eclipse Che with templates that include `org.eclipse.che_chebackupserverconfigurations_crd.yaml` CRD file definition.
=> Take into account CheBackupServerConfiguration CRD when deploying Che

README.md, src/commands/server/deploy.ts, src/commands/server/update.ts, yarn.lock
Fixes description of `--che-operator-image` flag by adding note that the falg is applicable for OLM installer too.
N/A
N/A
Check readme file
=> Fix `--che-operator-image` flag description

src/constants.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts, src/tasks/installers/operator.ts
Make sure that DWCO related objects are deleted during che-operator uninstallation instead of devworkspace uninstallation.
This only makes sense when the referenced issues are merged.
eclipse/che#19402
eclipse/che#19847
1. Install Che using the operator
2. Delete the Che installation using `chectl server:delete`
3. Make sure it works OK
```
oc get clusterroles | grep devworkspace-che
oc get roles -n eclipse-che | grep devworkspace-che
oc get rolebindings -n eclipse-che | grep devworkspace-che
oc get clusterrolebindings -n eclipse-che | grep devworkspace-che
```
4. Install Che using the operator again
5. Enable devworkspaces
```
oc patch checluster eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]'
```
6. Delete the Che …
=> feat: Remove the explicit DWCO (un)installation steps.

src/api/context.ts, src/api/version.ts, src/commands/server/update.ts, src/constants.ts, src/tasks/installers/common-tasks.ts
Fixes update from stable Eclipse Che to `next` version in case of operator installer.
https://github.com/eclipse/che/issues/20086
This issue [was discovered](https://github.com/che-incubator/chectl/pull/1348#issuecomment-874696938) while investigating `e2e update tests` failure in https://github.com/che-incubator/chectl/pull/1348.
Deploy stable Che and try to update to `next` version.
=> fix: Eclipse Che update in case of operator installer

.vscode/launch.json, package.json, prepare-che-operator-templates.js, yarn.lock
Use new templates locations.
https://github.com/eclipse/che/issues/19466
N/A
=> chore: Use new templates locations.

src/tasks/component-installers/devfile-workspace-operator-installer.ts, yarn.lock
Update dependency, remove Issuer creation from chectl
N/A
https://github.com/eclipse-che/che-operator/pull/932
https://github.com/eclipse/che-docs/pull/2064
N/A
=> chore: Update dependency, remove Issuer creation from chectl

.github/PULL_REQUEST_TEMPLATE.md
This is not an Eclipse project, we should not require the ECA check.
=> Remove Eclipse ECA checkbox in PR template

src/commands/server/deploy.ts, src/tasks/che.ts, src/tasks/installers/common-tasks.ts
Don't print keycloak credentials if `nativeUserMode: true`
```
✔ Eclipse Che status check...done
✔ Retrieving Che self-signed CA certificate...OK
✔ Prepare post installation output...done
✔ Show important messages
✔ Eclipse Che 7.35.0-SNAPSHOT has been successfully deployed.
✔ Documentation             : https://www.eclipse.org/che/docs/
✔ Users Dashboard           : https://che-eclipse-che.apps.ci-ln-lzv1012-f76d1.origin-ci-int-gce.dev.openshift.com
✔ HTPasswd user credentials : "che:3SoBty".
✔ Plug-in Registry          : …
```
=> fix: Don't print keycloak credentials if `nativeUserMode: true`

src/api/github-client.ts, src/api/version.ts, test/api/version.test.ts
Adds a separate comparator for chectl versions instead of just using `semver.gt`.
The new comparator can compare releases made on the same day by commit hashes (in such case there is a need to query commit info from Github to compare datetime of the commits)
https://github.com/eclipse/che/issues/20135
This is not trivial. Better take a look at tests.
=> fix: release versions comparator

src/api/context.ts, src/api/kube.ts, src/commands/server/deploy.ts, src/constants.ts, src/tasks/installers/olm.ts, test/e2e/e2e-upgrade.test.ts
Add support for stable-all-namespaces channel.
https://github.com/eclipse-che/che-operator/pull/890
Issue: https://github.com/eclipse/che/issues/19891
=> feat: Add support to install che using stable-all-namespaces olm channel

src/tasks/che.ts, src/tasks/installers/common-tasks.ts
Signed-off-by: Michal Vala <mvala@redhat.com>
`nativeUserMode` will be enabled by default on openshift with devworkspaces by https://github.com/eclipse-che/che-operator/pull/978. We need to reflect this in chectl so it does not wait for keycloak deployment.
Because `auth.nativeUserMode` is dynamicaly changed by che-operator, we don't know the value at the moment of listing the tasks. Current implementation gets and checks the current value in Keycloak deploy task. If we're deploying in `nativeUserMode: true`, the task is skipped (see the screenshot).
Looks like this now:
https://github.com/eclipse/che/issues/20203
1. deploy with `./bin/run server:deploy --platform=openshift --installer=operator --workspace-engine=dev-workspace --che-operator-image=quay.io/mvala/che-operator:gh20203-nativeU …
=> feat: detect nativeUserMode will be enabled so don't wait for keycloak

src/api/che.ts, src/api/kube.ts, src/commands/server/update.ts, src/tasks/installers/olm.ts
Implements mechanism of finding operator group of Che operator instead of using hardcoded name.
N/A
https://github.com/eclipse/che/issues/20424
1. Manually create a subscription for Che, for example:
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: eclipse-che
namespace: eclipse-che
spec:
channel: stable
installPlanApproval: Automatic
source: comunity-operators
sourceNamespace: openshift-marketplace
startingCSV: eclipse-che.v7.36.2
```
2. Check that an operator group is created by OLM (with a generated name)
3. Run `server:delete` command
4. Check that the operator group is gone
[As the author of this Pull Request I made sure …
=> fix: Detect Che operator group name instead of using hardcoded constant

src/api/kube.ts, src/util.ts, test/api/kube.test.ts
Fixes comparison of secrets data and recreation in case if secrets should be replaced
N/A
https://issues.redhat.com/browse/CRW-2314
1. Create a backup into an external backup server
2. Create a backup into another backup server by providing server credentials in command line
=> fix: backup/restore credentials change case

README.md, src/api/backup-restore.ts, src/api/context.ts, src/api/kube.ts, src/api/typings/backup-restore-crds.d.ts, src/commands/server/backup.ts, src/commands/server/deploy.ts, src/commands/server/restore.ts, src/constants.ts, src/tasks/installers/common-tasks.ts, src/tasks/installers/installer.ts, src/tasks/installers/olm.ts, src/tasks/installers/operator.ts, src/util.ts
Implements ability to restore to a different version of Che than deployed operator.
It added several new falgs to `server:restore` command:
`--rollback` - finds backup made automatically and restores Che operator to the previous version and restore installation from the backup
`--backup-cr` - restores Che from given backup described by a backup object (it includes Che version as well)
`--version` - before restoring Che installation, deploys given version of Che Operator (usually used together with `--snapshot-id`)
https://issues.redhat.com/browse/CRW-1497
1. Edit latest CSV for OLM stable channel: increment version everywhere, change replace version to the one being replaced. Optionally change operator image.
2. Build test catalog source with the following command:
```sh …
```
=> feat: Implement version rollback for server restore

src/api/kube.ts, src/tasks/installers/olm.ts
If operator is installed in from the `tech-preview` channel then subscription is created there as well.
In this case fetching CR from CSV failed since subscription was supposed to be created on che namespace only.
N/A
https://issues.redhat.com/browse/CRW-2320
See https://issues.redhat.com/browse/CRW-2320
=> fix: use operator namespace to get checluster CR from a csv

src/constants.ts, src/tasks/component-installers/devfile-workspace-operator-installer.ts
https://issues.redhat.com/browse/CRW-2363
1. Install Che using OLM installer:
```bash
./run server:deploy --installer olm -p openshift --olm-channel=tech-preview-stable-all-namespaces
```
2. Uninstall Che:
```bash
./run server:delete -n eclipse-che -y
```
3. Install one more time using 1 step again. Re-installation should be successfull.
=> fix: re-deploy Che via OLM installer.

resources/dex/configmap.yaml, src/commands/server/deploy.ts, src/tasks/component-installers/dex.ts
Signed-off-by: Michal Vala <mvala@redhat.com>
- fixes dex configuration to set oauth callback without subdomain, where che is really deployed
- sets identity provider url to dex service in checluster CR
- don't show warning message when native user mode is enabled
https://github.com/eclipse/che/issues/20635
```
cat EOF << > /tmp/patch.yaml
spec:
auth:
nativeUserMode: true
EOF
chectl server:deploy \
--installer operator \
--platform minikube \
--che-operator-image quay.io/mvala/che-operator:gh20635-nativeAuthKube \
--che-operator-cr-patch-yaml /tmp/patch.yaml
```
after deploy, install dex certificate into the browser and open che url. …
=> fix: fix dex configuration, set identity provider in checluster

src/api/kube.ts, src/commands/server/deploy.ts, src/tasks/che.ts, src/util.ts, yarn.lock
Enable native user mode if devworkspace engine is enabled
```
✔ Show important messages
✔ Eclipse Che 7.41.0-SNAPSHOT has been successfully deployed.
✔ Documentation             : https://www.eclipse.org/che/docs/
✔ Users Dashboard           : https://192.168.99.100.nip.io
✔ Admin user login          : "admin:admin". NOTE: must change after first login.
✔ Plug-in Registry          : https://192.168.99.100.nip.io/plugin-registry/v3/
✔ Devfile Registry          : https://192.168.99.100.nip.io/devfile-registry/
✔ ---------------------------------------------------------------------- …
```
=> chore: enable native user mode if devworkspace engine is enabled

.ci/oci_chectl_rollback.sh, .github/workflows/e2e-minikube-operator-rollback.yml, src/api/kube.ts, test/e2e/e2e-rollback.test.ts, test/e2e/util.ts
Fixes rollback tests for OLM installer by getting available versions not from GitHub tags, but from community-operators repository.
Also adds rollback test for Operator installer on Minikube using GitHub action.
N/A
https://github.com/eclipse/che/issues/20585
Rollback tests must succeed.
=> fix: rollback tests

README.md, package.json, src/commands/server/deploy.ts, src/tasks/installers/common-tasks.ts, yarn.lock
Adds a new check that ensures k8s cluster has OIDC provider installed and configured.
The only exception is `minikube` as Dex is automatically installed.
In case of missing OIDC provider on a k8s cluster:
In case of `minikube`:
In case if Che is already installed, the check is disabled (and not displayed).
https://github.com/eclipse/che/issues/20909
Try to deploy Che using `chectl server:deploy --platform=k8s --domain=****`.
Deployment should fail if he cluster misses an OIDC provider installed and k8s API server configured to use it.
Reviewers, please comment how you tested the PR when …
=> feat: Add pre-install task to check if an OIDC provider is installed

src/commands/server/deploy.ts, src/constants.ts, yarn.lock
Add doc link how to configure OIDC Identity Provider in an error message
```
Error: API server is not configured with OIDC Identity Provider, see details https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server. To bypass OIDC Provider check use '--skip-oidc-provider-check' flag
```
https://github.com/eclipse/che/issues/20909
N/A
=> chore: Add doc link how to configure OIDC Identity Provider

src/api/che.ts, src/api/version.ts, src/commands/server/status.ts, src/tasks/che.ts, test/api/che.test.ts
* print only Dex credentials if DevWorkspace enabled
* fix printing dashboard ulr
* fix detecting che version
```
✔ Show important messages
✔ Eclipse Che 'next' has been successfully deployed.
✔ Documentation             : https://www.eclipse.org/che/docs/
✔ Users Dashboard           : https://192.168.59.100.nip.io/dashboard/
✔ Plug-in Registry          : https://192.168.59.100.nip.io/plugin-registry/v3/
✔ Devfile Registry          : https://192.168.59.100.nip.io/devfile-registry/
✔ Dex user …
```
=> fix: print only Dex credentials if DevWorkspace enabled

.ci/openshift-ci/Dockerfile, .github/workflows/codecov.yml, .github/workflows/happy-path.yml, .github/workflows/minikube-chectl-commands-tests.yml, .github/workflows/minikube-chectl-release-test.yml, .github/workflows/pr-check.yml, .github/workflows/release-build-and-push-to-GH-releases.yml, .github/workflows/release.yml, package.json, src/tasks/platforms/docker-desktop.ts
* Use NodeJS 16
* Unify PRs checks
N/A
https://github.com/eclipse/che/issues/21075
N/A
=> ci: Use NodeJS 16

src/api/kube.ts, src/tasks/installers/olm-dev-workspace-operator.ts, src/tasks/installers/olm.ts
Setting custom image for che-operator
N/A
https://github.com/eclipse/che/issues/21106
```
run server:deploy \
--platform=openshift \
--workspace-engine=dev-workspace \
-n openshift-operators \
--no-olm-suggested-namespace \
--che-operator-image=<customiamge>
```
Ensure, that che-operator uses the custom image
=> fix: Setting custom image for che-operator

src/tasks/che.ts
Includes logs from the `che-gateway` deployment in the `server:logs` command
N/A
Closes https://github.com/eclipse/che/issues/21312 
1. Execute `chectl server:logs`
2. Verify that /tmp/ directory includes logs from che-gateway containers
- [N/A] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [N/A] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [N/A] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTIN …
=> feat: Include Che Gateway logs in server:logs command

prepare-che-operator-templates.js, src/api/kube.ts, src/tasks/installers/operator.ts, yarn.lock
Support to create/update/delete ValidationWebhookConfiguration for CheCluster API v2
N/A
https://github.com/eclipse/che/issues/21577
N/A
=> chore: Support CheCluster API v2 ValidationWebhookConfiguration

src/tasks/installers/operator.ts, src/util.ts
* fix for updating ValidationgWebhookConfiguration
* set correct namespace for operator service on webhook config
* handle `failed calling webhook` error
N/A
https://github.com/eclipse/che/issues/21577
N/A
=> fix: Update ValidationgWebhookConfiguration

src/api/kube.ts, src/tasks/installers/operator.ts, test/e2e/e2e-upgrade.test.ts
feat: add ValidationWebhookConfiguration
N/A
https://github.com/eclipse/che/issues/21577
N/A
=> feat: add ValidationWebhookConfiguration

prepare-che-operator-templates.js, yarn.lock
fix: add ValidatingWebhookConfiguration
N/A
N/A
N/A
=> fix: add ValidatingWebhookConfiguration

.vscode/extensions.json, .vscode/launch.json, .vscode/tasks.json, CONTRIBUTING.md, devfile.yaml, package.json
Removed Generate Devfile and Create Workspace sections and edited the command documentation to reflect how commands are currently run.
Signed-off-by: Samantha Dawley <sdawley@redhat.com>
Addresses: https://github.com/eclipse/che/issues/21363 
=> Updating CONTRIBUTING.md for eclipse/che#21363

src/api/che-logs-reader.ts, src/tasks/platforms/crc.ts, src/tasks/platforms/docker-desktop.ts, src/tasks/platforms/k8s.ts, src/tasks/platforms/microk8s.ts, src/tasks/platforms/minikube.ts, src/tasks/platforms/openshift.ts, src/utils/utls.ts
Improve check if command exists before running chectl tasks.
Double check with ignoring local non executable files.
N/A
https://github.com/eclipse/che/issues/21884
=> fix: Improve checking command existence

.ci/oc-test-happy-path.sh
According to task  #[22043](https://github.com/eclipse/che/pull/22043) test scripts were updated, necessary changes added to this repository.
PR: [#22052](https://github.com/eclipse/che/pull/22052)
The old npm script "test-empty-workspace-devworkspace-happy-path-code" runs one test spec file - "EmptyWorkspace.spec.ts" from the test [directory](https://github.com/eclipse/che/tree/main/tests/e2e/tests/devfiles/che-code) and uses hard-coded mocha config.
It was replaced with "test-all-devfiles" which uses new dynamic mocha config and will run the same file if variable "USERSTORY=EmptyWorkspace" or all test specs in the test directory if variable not set. 
N/A
Run happy-pass PR check.
[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING …
=> Updated oc-test-happy-path.sh according to new test scripts in "Che" project

.ci/openshift-ci/Dockerfile
chore: Revert Dockerfile for OpenShift CI
=> chore: Revert Dockerfile for OpenShift CI

.github/workflows/minikube-chectl-release-test.yml, .github/workflows/pr-check.yml, .github/workflows/release-build-and-push-to-GH-releases.yml, .vscode/tasks.json, CONTRIBUTING.md, README.md, bin/shasum, package.json, yarn.lock
chore: fix: update to oclif v3 instead of archived/obsolete oclif-dev v1
Change-Id: Ie5148a80ba50f1a125eebd6f10e2f099d276ee59
N/A
related to https://issues.redhat.com/browse/CRW-4855
N/A
=> chore: fix: update to oclif v3 instead of archived/obsolete oclif-dev v1

devfile.yaml
chore: add build command to devfile
Change-Id: I90831fdd3ab07af88eec79a270425f34b300fd3b
N/A
followup to https://github.com/che-incubator/chectl/pull/2743
related to https://issues.redhat.com/browse/CRW-4855
N/A
=> chore: add build command to devfile

make-release.sh
chore: instead of just having a VERSION file, bump chectl version to match release version (0.0.2 --> 7.yy.0)
Change-Id: Id9133f0e7f6bb738f8625fd3bdc79730df6a004e
N/A
Sort of related to https://issues.redhat.com/browse/CRW-4922 -- discovered while trying to figure out what's borked there. 
1. check out branch
2. `yarn`
3. `./bin/run --help` to see the version
4. can also build binaries with `yarn pack-binaries` and then install from one of those
=> chore: instead of just having a VERSION file, bump chectl version to match release version (0.0.2 --> 7.yy.0)

.github/workflows/codecov.yml, .github/workflows/minikube-chectl-commands-tests.yml, .github/workflows/minikube-chectl-release-test.yml, .github/workflows/pr-check.yml, .github/workflows/release-build-and-push-to-GH-releases.yml, .github/workflows/release.yml
use latest node 18.18.0 in workflows
Change-Id: Id9133f0e7f6bb738f8625fd3bdc79730df6a004e
bump copyrights
Change-Id: I3bc89c21ae5b5255559684ff9682564aa7729bcf
N/A
none; this might also be unsafe due to https://github.com/microsoft/vscode/issues/194665
N/A
=> use latest node 18.18.0 in workflows

.github/workflows/release.yml, src/tasks/installers/eclipse-che/eclipse-che-tasks.ts, test/e2e/e2e-upgrade-version.test.ts
* Fix e2e chectl upgrade test
* Fix `getDiscoverUpgradeImagePathTas` task title
* Fix release commit author 
N/A
N/A
N/A
=> fix: e2e tests, task title

.github/workflows/minikube-chectl-commands-tests.yml, .github/workflows/minikube-chectl-release-test.yml, src/tasks/che-tasks.ts, src/tasks/pod-tasks.ts, yarn.lock
fix: Don't fail on scale down if deployment does not exist
N/A
https://github.com/eclipse/che/issues/22485
N/A
=> fix: Don't fail on scale down if deployment does not exist

src/api/types/che-cluster.ts, src/tasks/pod-tasks.ts, src/utils/che.ts
Inspect CheCluster for embedded plugin registry indicator
N/A
https://github.com/eclipse/che/issues/22840
N/A
=> fix: Inspect CheCluster for embedded plugin registry indicator

src/api/kube-client.ts, src/tasks/installers/eclipse-che/eclipse-che-tasks.ts
fix: Update che-operator in a different namespace than eclipse-che
N/A
N/A
1. Deploy Eclipse Che in a `che` namespace
2. Update eclipse che with `bin/run server:udpate -n che` command
=> fix: Update che-operator in a different namespace than eclipse-che

src/tasks/che-tasks.ts
fix: Increase waiting che active timeout
N/A
N/A
N/A
=> fix: Increase waiting che active timeout

src/tasks/pod-tasks.ts, src/utils/che.ts, yarn.lock
chore: Adapt chectl to 22932
N/A
https://github.com/eclipse-che/che/issues/22932
=> chore: Adapt chectl to 22932

src/api/kube-client.ts, src/tasks/installers/dev-workspace/dev-workspace-tasks.ts
Fixes the DWO pod timeout issue when running `chectl server:deploy -p openshift`:
```
✖ Wait for Dev Workspace operator ready
→ ERR_TIMEOUT: Timeout set to pod ready timeout 60000
Create Subscription eclipse-che
Eclipse Che Operator pod bootstrap
Fetch CheCluster sample from a CSV
Create CheCluster Custom Resource
Error: Command server:deploy failed with the error: ERR_TIMEOUT: Timeout set to pod ready timeout 60000 See details: /home/vsvydenko/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1720444057431.
at newError (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/lib/utils/utls.js:39:19)
at wrapCommandError (/home/vsvydenko/.local/share/chectl/client/0.0.20240702-next.8e77812/lib/utils/command-utils.js:54:32)
at Deploy.<anonymous> …
```
=> fix: allow wait for multiple DWO webhook pods

src/api/kube-client.ts
Update CRD before deletion in 2 steps
N/A
https://issues.redhat.com/browse/CRW-6892
=> chore: Update CRD before deletion in 2 steps

src/api/kube-client.ts
fix: issue with remove checluster CRD
N/A
https://issues.redhat.com/browse/CRW-7558
=> fix: issue with remove checluster CRD

src/api/kube-client.ts
fix: Increase timeout to wait installplan
N/A
```
04:38:25  [22:38:13] Create Subscription eclipse-che [failed]
04:38:25  [22:38:13] → undefined
04:38:25  [22:38:13] Deploy Eclipse Che [failed]
04:38:25  [22:38:13] → Cannot create property 'context' on string 'Timeout reached while waiting for "install-lr522" has go status 'Installed'.'
04:38:25  Error: Command server:deploy failed with the error: Cannot create property 'context' on string 'Timeout reached while waiting for "install-lr522" has go status 'Installed'.' See details: /home/hudson/.cache/chectl/error.log. Eclipse Che logs: /tmp/chectl-logs/1748486221076.
04:38:25      at newError (/usr/local/lib/chectl/lib/utils/utls.js:39:19)
04:38:25      at wrapCommandError (/usr/local/lib/chectl/lib/utils/command-utils.js:54:32)
04:38:25 …
```
=> fix: Increase timeout to wait installplan

src/tasks/platforms/minikube.ts
Add support minikube none driver.
```sh
root@kubernetes:/home/mikoto/chectl# minikube ssh
❌  Exiting due to MK_USAGE: 'none' driver does not support 'minikube ssh' command
root@kubernetes:/home/mikoto/chectl# ./bin/chectl server:deploy --platform minikube
Enable CLI usage data to be sent to Red Hat online services. More info: https://developers.redhat.com/article/tool-data-collection [y/n]: y
› Current Kubernetes context: 'minikube'
✔ Verify Kubernetes API...[1.33]
✔ Minikube preflight checklist
✔ Verify if kubectl is installed...[OK]
✔ Verify if minikube is installed...[OK]
✔ Verify if minikube is running...[OK]
✔ Enable minikube ingress addon...[Enabled]
✔ Retrieving minikube IP and domain for ingress URLs...[192.168.1.38.nip.io]
✔ Checking minikube version...[1.36.0]
✔ Create Namespace …
```
=> feat: Add support minikube none driver.
